  {'Asset class Stock': 95.5,
  'Asset class Cash': 4.0,
  'Asset class Other': 0.5,
  'Asset class Bond': 0.1,
  'Region Developed country': 67.8,
  'Region Emerging Market': 27.7,
  'Region Asia - Emerging': 20.8,
  'Region United States': 20.3,
  'Region United Kingdom': 14.6,
  'Region Asia - Developed': 13.6,
  'Region Eurozone': 9.9,
  'Region Japan': 4.5,
  'Region Latin America': 4.5,
  'Region Europe - ex euro': 3.5,
  'Region Africa': 1.7,
  'Region Europe - Emerging': 0.6,
  'Region Other': 1.3,
  'Sector Financial services': 20.0,
  'Sector Technology': 18.4,
  'Sector Industrials': 13.9,
  'Sector Consumer cyclical': 9.7,
  'Sector Communication Services': 7.8,
  'Sector Consumer defensive': 7.5,
  'Sector Healthcare': 7.3,
  'Sector Basic materials': 4.3,
  'Sector Cash & equivalents': 4.0,
  'Sector Utilities': 2.8,
  'Sector Energy': 2.5,
  'Sector Real estate': 1.1,
  'Sector Other': 0.1,
  'Top 10 holdings Other': 19.0,
  'Asset class Bond': 50.9,
  'Asset class Cash': 29.1,
  'Asset class Stock': 14.9,
  'Asset class Other': 4.5,
  'Asset class Convertible': 0.5,
  'Asset class Preferred': 0.1,
  'Region Developed country': 14.1,
  'Region United States': 5.7,
  'Region United Kingdom': 3.9,
  'Region Eurozone': 1.9,
  'Region Japan': 1.1,
  'Region Europe - ex euro': 0.7,
  'Region Emerging Market': 0.6,
  'Region Asia - Developed': 0.5,
  'Region Asia - Emerging': 0.5,
  'Region Canada': 0.2,
  'Region Australasia': 0.1,
  'Region Latin America': 0.1,
  'Region Other': 0.1,
  'Top 10 holdings Other': 20.1,
  'Sector  Government': 40.8,
  'Sector Cash & equivalents': 24.2,
  'Sector Corporate': 11.4,
  'Sector Securitized': 4.4,
  'Sector Industrials': 2.5,
  'Sector Real estate': 2.2,
  'Sector Financial services': 2.1,
  'Sector Technology': 2.1,
  'Sector Healthcare': 1.5,
  'Sector Consumer defensive': 1.3,
  'Sector Communication Services': 1.1,
  'Sector Consumer cyclical': 1.0,
  'Sector Other': 1.6,
  'Currency Other': 0.4,
  'Asset class Bond': 59.0,
  'Asset class Stock': 25.1,
  'Asset class Cash': 9.6,
  'Asset class Other': 5.6,
  'Asset class Convertible': 0.7,
  'Asset class Preferred': 0.1,
  'Region Developed country': 23.8,
  'Region United States': 9.8,
  'Region United Kingdom': 6.4,
  'Region Eurozone': 3.3,
  'Region Japan': 1.8,
  'Region Europe - ex euro': 1.3,
  'Region Emerging Market': 1.2,
  'Region Asia - Emerging': 0.9,
  'Region Asia - Developed': 0.8,
  'Region Canada': 0.2,
  'Region Latin America': 0.2,
  'Region Australasia': 0.2,
  'Region Other': 0.1,
  'Top 10 holdings Other': 31.3,
  'Sector Government': 43.3,
  'Sector Corporate': 15.8,
  'Sector Cash & equivalents': 8.2,
  'Sector Industrials': 4.3,
  'Sector Technology': 3.6,
  'Sector Financial services': 3.6,
  'Sector Real estate': 2.9,
  'Sector Healthcare': 2.6,
  'Sector Consumer defensive': 2.2,
  'Sector Communication Services': 2.0,
  'Sector Securitized': 2.0,
  'Sector Consumer cyclical': 1.7,
  'Sector Other': 2.9,
  'Currency Other': 0.7,
  'Asset class Bond': 44.5,
  'Asset class Stock': 41.5,
  'Asset class Cash': 6.6,
  'Asset class Other': 6.6,
  'Asset class Convertible': 0.8,
  'Asset class Preferred': 0.1,
  'Region Developed country': 39.3,
  'Region United States': 16.1,
  'Region United Kingdom': 10.4,
  'Region Eurozone': 5.5,
  'Region Japan': 3.1,
  'Region Europe - ex euro': 2.2,
  'Region Emerging Market': 2.1,
  'Region Asia - Emerging': 1.6,
  'Region Asia - Developed': 1.4,
  'Region Latin America': 0.4,
  'Region Canada': 0.3,
  'Region Australasia': 0.2,
  'Region Other': 0.2,
  'Sector Government': 31.7,
  'Sector Corporate': 13.3,
  'Sector Industrials': 7.1,
  'Sector Technology': 6.2,
  'Sector Financial services': 6.1,
  'Sector Cash & equivalents': 5.5,
  'Sector Healthcare': 4.5,
  'Sector Consumer defensive': 3.7,
  'Sector Real estate': 3.5,
  'Sector Communication Services': 3.4,
  'Sector Consumer cyclical': 3.0,
  'Sector Basic materials': 2.2,
  'Sector Other': 4.3,
  'Top 10 holdings Other': 44.1,
  'Asset class Stock': 50.7,
  'Asset class Bond': 35.8,
  'Asset class Other': 6.6,
  'Asset class Cash': 6.0,
  'Asset class Convertible': 0.8,
  'Asset class Preferred': 0.1,
  'Region Developed country': 47.6,
  'Region United States': 19.5,
  'Region United Kingdom': 12.5,
  'Region Eurozone': 6.7,
  'Region Japan': 3.7,
  'Region Emerging Market': 2.9,
  'Region Europe - ex euro': 2.8,
  'Region Asia - Emerging': 2.2,
  'Region Asia - Developed': 1.8,
  'Region Latin America': 0.5,
  'Region Canada': 0.3,
  'Region Australasia': 0.2,
  'Region Other': 0.3,
  'Sector Government': 23.8,
  'Sector Corporate': 12.7,
  'Sector Industrials': 8.6,
  'Sector Technology': 7.7,
  'Sector Financial services': 7.5,
  'Sector Healthcare': 5.5,
  'Sector Cash & equivalents': 4.9,
  'Sector Consumer defensive': 4.6,
  'Sector Communication Services': 4.2,
  'Sector Consumer cyclical': 3.7,
  'Sector Real estate': 3.6,
  'Sector Basic materials': 2.7,
  'Sector Other': 4.9,
  'Top 10 holdings Other': 48.8,
  'Asset class Stock': 64.3,
  'Asset class Bond': 23.5,
  'Asset class Other': 6.4,
  'Asset class Cash': 5.1,
  'Asset class Convertible': 0.7,
  'Asset class Preferred': 0.0,
  'Region Developed country': 59.5,
  'Region United States': 24.3,
  'Region United Kingdom': 15.4,
  'Region Eurozone': 8.3,
  'Region Emerging Market': 4.6,
  'Region Japan': 4.6,
  'Region Europe - ex euro': 3.5,
  'Region Asia - Emerging': 3.5,
  'Region Asia - Developed': 2.7,
  'Region Latin America': 0.8,
  'Region Canada': 0.4,
  'Region Africa': 0.3,
  'Region Other': 0.4,
  'Sector Government': 15.6,
  'Sector Industrials': 10.9,
  'Sector Technology': 10.0,
  'Sector Financial services': 9.8,
  'Sector Corporate': 8.8,
  'Sector Healthcare': 7.0,
  'Sector Consumer defensive': 5.8,
  'Sector Communication Services': 5.4,
  'Sector Consumer cyclical': 4.8,
  'Sector Cash & equivalents': 4.2,
  'Sector Real estate': 3.6,
  'Sector Basic materials': 3.4,
  'Sector Other': 5.4,
  'Top 10 holdings Other': 47.2,
  'Asset class Stock': 75.3,
  'Asset class Bond': 12.7,
  'Asset class Other': 5.9,
  'Asset class Cash': 5.5,
  'Asset class Convertible': 0.6,
  'Asset class Preferred': 0.0,
  'Region Developed country': 68.7,
  'Region United States': 27.7,
  'Region United Kingdom': 17.6,
  'Region Eurozone': 9.7,
  'Region Emerging Market': 6.4,
  'Region Japan': 5.3,
  'Region Asia - Emerging': 4.8,
  'Region Europe - ex euro': 4.0,
  'Region Asia - Developed': 3.6,
  'Region Latin America': 1.1,
  'Region Africa': 0.4,
  'Region Canada': 0.4,
  'Region Other': 0.5,
  'Sector Industrials': 12.6,
  'Sector Technology': 12.0,
  'Sector Financial services': 11.8,
  'Sector Government': 9.3,
  'Sector Healthcare': 8.1,
  'Sector Consumer defensive': 6.8,
  'Sector Communication Services': 6.3,
  'Sector Consumer cyclical': 5.7,
  'Sector Cash & equivalents': 4.6,
  'Sector Corporate': 4.6,
  'Sector Basic materials': 3.9,
  'Sector Utilities': 3.6,
  'Sector Other': 5.7,
  'Top 10 holdings Other': 43.6,
  'Asset class Stock': 87.0,
  'Asset class Cash': 5.3,
  'Asset class Other': 3.9,
  'Asset class Bond': 3.3,
  'Asset class Convertible': 0.4,
  'Asset class Preferred': 0.0,
  'Region Developed country': 77.7,
  'Region United States': 30.8,
  'Region United Kingdom': 19.6,
  'Region Eurozone': 11.1,
  'Region Emerging Market': 9.2,
  'Region Asia - Emerging': 6.9,
  'Region Japan': 5.9,
  'Region Asia - Developed': 5.0,
  'Region Europe - ex euro': 4.6,
  'Region Latin America': 1.5,
  'Region Africa': 0.6,
  'Region Canada': 0.4,
  'Region Other': 0.6,
  'Sector Industrials': 14.3,
  'Sector Technology': 14.2,
  'Sector Financial services': 14.1,
  'Sector Healthcare': 9.2,
  'Sector Consumer defensive': 7.8,
  'Sector Communication Services': 7.3,
  'Sector Consumer cyclical': 6.8,
  'Sector Cash & equivalents': 4.8,
  'Sector Basic materials': 4.4,
  'Sector Utilities': 3.9,
  'Sector Government': 3.7,
  'Sector Real estate': 3.4,
  'Sector Other': 3.0,
  'Top 10 holdings Other': 34.8,
  'Asset class Stock': 95.1,
  'Asset class Cash': 4.2,
  'Asset class Other': 0.7,
  'Asset class Bond': 0.0,
  'Region Developed country': 78.8,
  'Region United States': 29.1,
  'Region United Kingdom': 18.9,
  'Region Emerging Market': 16.3,
  'Region Asia - Emerging': 12.2,
  'Region Eurozone': 11.3,
  'Region Asia - Developed': 8.2,
  'Region Japan': 5.8,
  'Region Europe - ex euro': 4.5,
  'Region Latin America': 2.6,
  'Region Africa': 1.0,
  'Region Canada': 0.4,
  'Region Other': 0.8,
  'Sector Financial services': 17.2,
  'Sector Technology': 16.8,
  'Sector Industrials': 15.1,
  'Sector Healthcare': 9.3,
  'Sector Consumer cyclical': 8.3,
  'Sector Consumer defensive': 8.2,
  'Sector Communication Services': 8.1,
  'Sector Basic materials': 4.7,
  'Sector Cash & equivalents': 4.2,
  'Sector Utilities': 3.7,
  'Sector Energy': 2.6,
  'Sector Real estate': 1.1,
  'Sector Other': 0.0,
  'Top 10 holdings Other': 28.6,
  'Asset class Government bonds': 31.9,
  'Asset class Liquid Assets': 17.1,
  'Asset class Alternatives': 9.8,
  'Asset class Aggregate Bonds': 8.8,
  'Asset class Global Equity': 5.9,
  'Asset class  UK Equity': 5.0,
  'Asset class Investment Grade Bonds': 4.4,
  'Asset class USA Equity': 3.9,
  'Asset class Emerging Market Debt Bonds': 3.5,
  'Asset class Property': 2.6,
  'Asset class Absolute Return': 2.5,
  'Asset class Europe Equity': 2.2,
  'Asset class Japan Equity': 0.9,
  'Asset class Other Equity': 0.7,
  'Asset class Emerging Market Equity': 0.7,
  'Region Global': 46.3,
  'Region Europe ex-UK/Middle East': 32.8,
  'Region United Kingdom': 13.8,
  'Region Americas': 3.9,
  'Region Liquid Assets': 2.0,
  'Region Japan': 0.9,
  'Region Pacific ex-Japan': 0.3,
  'Asset class Government bonds': 20.8,
  'Asset class Liquid Assets': 13.5,
  'Asset class Alternatives': 11.3,
  'Asset class Global Equity': 10.4,
  'Asset class UK Equity': 8.4,
  'Asset class Aggregate Bonds': 7.2,
  'Asset class USA Equity': 7.1,
  'Asset class Europe Equity': 4.0,
  'Asset class Investment Grade Bonds': 3.7,
  'Asset class Property': 3.0,
  'Asset class Emerging Market Debt  Bonds': 3.0,
  'Asset class Absolute Return': 3.0,
  'Asset class Japan Equity': 1.7,
  'Asset class Other Equity': 1.3,
  'Asset class Emerging Market Equity': 1.2,
  'Region Global': 46.9,
  'Region Europe ex-UK/Middle East': 27.9,
  'Region United Kingdom': 13.6,
  'Region Americas': 7.1,
  'Region Liquid Assets': 2.3,
  'Region Japan': 1.7,
  'Region Pacific ex-Japan': 0.6,
  'Asset class Liquid Assets': 13.9,
  'Asset class Government bonds': 13.1,
  'Asset class Global Equity': 12.8,
  'Asset class Alternatives': 11.4,
  'Asset class UK Equity': 10.2,
  'Asset class USA Equity': 8.9,
  'Asset class Aggregate Bonds': 6.8,
  'Asset class Europe Equity': 4.8,
  'Asset class Investment Grade Bonds': 3.4,
  'Asset class Absolute Return': 3.0,
  'Asset class Property': 3.0,
  'Asset class Emerging Market Debt Bonds': 2.8,
  'Asset class Japan Equity': 2.0,
  'Asset class Emerging Market Equity': 1.7,
  'Asset class Other Equity': 1.6,
  'Region Global': 46.4,
  'Region  Europe ex-UK/Middle East': 24.2,
  'Region United Kingdom': 15.0,
  'Region Americas': 8.9,
  'Region Liquid Assets': 2.7,
  'Region Japan': 2.0,
  'Region Pacific ex-Japan': 0.8,
  'Asset class Global Equity': 17.4,
  'Asset class UK Equity': 12.7,
  'Asset class USA Equity': 11.4,
  'Asset class Liquid Assets': 11.2,
  'Asset class Alternatives': 11.0,
  'Asset class Government bonds': 7.5,
  'Asset class Europe Equity': 5.9,
  'Asset class Aggregate Bonds': 4.6,
  'Asset class Emerging Market Equity': 2.9,
  'Asset class Property': 2.8,
  'Asset class Absolute Return': 2.8,
  'Asset class Japan Equity': 2.5,
  'Asset class Investment Grade Bonds': 2.4,
  'Asset class Other Equity': 1.9,
  'Asset class Emerging Market Debt Bonds': 1.8,
  'Region Global': 45.7,
  'Region  Europe ex-UK/Middle East': 20.9,
  'Region United Kingdom': 16.0,
  'Region Americas': 11.4,
  'Region Japan': 2.5,
  'Region Liquid Assets': 2.2,
  'Region Pacific ex-Japan': 1.3,
  'Asset class Global Equity': 21.6,
  'Asset class UK Equity': 14.4,
  'Asset class USA Equity': 12.9,
  'Asset class Liquid Assets': 10.8,
  'Asset class Alternatives': 9.6,
  'Asset class Europe Equity': 6.8,
  'Asset class Emerging Market Equity': 4.0,
  'Asset class Government bonds': 3.8,
  'Asset class Japan Equity': 2.8,
  'Asset class Property': 2.6,
  'Asset class Absolute Return': 2.5,
  'Asset class Other Equity': 2.4,
  'Asset class Aggregate Bonds': 2.0,
  'Asset class Asia Pacific ex Japan Equity': 1.9,
  'Asset class Investment Grade Bonds': 1.0,
  'Region Global': 43.8,
  'Region Europe ex-UK/Middle East': 18.1,
  'Region United Kingdom': 17.5,
  'Region Americas': 12.9,
  'Region Japan': 2.8,
  'Region Liquid Assets': 2.8,
  'Region Pacific ex-Japan': 1.9,
  'Asset class Global Equity': 26.0,
  'Asset class UK Equity': 15.6,
  'Asset class USA Equity': 14.7,
  'Asset class Liquid Assets': 9.8,
  'Asset class Europe Equity': 7.8,
  'Asset class Emerging Market Equity': 6.0,
  'Asset class Alternatives': 6.0,
  'Asset class Japan Equity': 3.2,
  'Asset class Asia Pacific ex Japan Equity': 2.8,
  'Asset class Other Equity': 2.5,
  'Asset class Property': 2.4,
  'Asset class Government bonds': 1.6,
  'Asset class Absolute Return': 1.5,
  'Region Global': 42.2,
  'Region United Kingdom': 18.9,
  'Region Europe ex-UK/Middle East': 15.7,
  'Region Americas': 14.7,
  'Region Japan': 3.2,
  'Region Pacific ex-Japan': 2.8,
  'Region Liquid Assets': 2.5,
  'Asset class Global Equity': 42.1,
  'Asset class UK Equity': 15.3,
  'Asset class Investment Grade Bonds': 14.6,
  'Asset class Emerging Market Equity': 6.9,
  'Asset class USA Equity': 6.0,
  'Asset class Europe Equity': 4.9,
  'Asset class Government bonds': 3.3,
  'Asset class Japan Equity': 2.9,
  'Asset class Emerging Market Debt Bonds': 1.5,
  'Asset class Derivatives': 1.3,
  'Asset class Commodities': 0.8,
  'Asset class Liquid Assets': 0.4,
  'Asset class Investment Grade Bonds': 32.2,
  'Asset class Government bonds': 29.2,
  'Asset class Global Equity': 17.1,
  'Asset class Derivatives': 6.3,
  'Asset class UK Equity': 5.3,
  'Asset class Liquid Assets': 3.8,
  'Asset class Emerging Market Debt Bonds': 1.5,
  'Asset class Europe Equity': 1.5,
  'Asset class Emerging Market Equity': 0.9,
  'Asset class Japan Equity': 0.8,
  'Asset class Commodities': 0.7,
  'Asset class USA Equity': 0.5,
  'Top 10 holdings Cash': 3.8,
  'Asset class Global Equity': 41.4,
  'Asset class Investment Grade Bonds': 21.8,
  'Asset class UK Equity': 12.9,
  'Asset class Government bonds': 7.3,
  'Asset class Emerging Market Equity': 4.0,
  'Asset class Europe Equity': 3.8,
  'Asset class Japan Equity': 2.2,
  'Asset class USA Equity': 2.2,
  'Asset class Emerging Market Debt Bonds': 1.5,
  'Asset class Derivatives': 1.4,
  'Asset class Commodities': 0.8,
  'Asset class Liquid Assets': 0.6,
  'Asset class Investment Grade Bonds': 29.3,
  'Asset class Global Equity': 28.7,
  'Asset class Government bonds': 21.0,
  'Asset class UK Equity': 8.6,
  'Asset class Derivatives': 3.6,
  'Asset class Europe Equity': 2.4,
  'Asset class Japan Equity': 1.6,
  'Asset class Emerging Market Debt Bonds': 1.4,
  'Asset class Emerging Market Equity': 1.1,
  'Asset class USA Equity': 1.0,
  'Asset class Commodities': 0.8,
  'Asset class Liquid Assets': 0.5,
  'Asset class Investment Grade Bonds': 15.8,
  'Asset class Government bonds': 13.1,
  'Asset class Liquid Assets': 11.5,
  'Asset class UK Equity': 10.9,
  'Asset class USA Equity': 10.5,
  'Asset class Global Equity': 9.8,
  'Asset class Hedge Funds': 9.5,
  'Asset class Other': 5.0,
  'Asset class Europe Equity': 4.8,
  'Asset class Emerging Market Equity': 3.1,
  'Asset class Property': 3.0,
  'Asset class Emerging Market Debt Bonds': 2.8,
  'Asset class Asia Pacific ex Japan Equity': 0.2,
  'Region Other': 43.3,
  'Region United Kingdom': 29.0,
  'Region Europe ex-UK/Middle East': 14.9,
  'Region Europe (excluding UK)': 4.8,
  'Region Americas': 4.7,
  'Region Liquid Assets': 2.5,
  'Region Pacific ex-Japan': 0.8,
  'Asset class Liquid Assets': 55.5,
  'Asset class Government bonds': 20.0,
  'Asset class USA Equity': 9.9,
  'Asset class Derivatives': 9.7,
  'Asset class Europe Equity': 1.3,
  'Asset class Commodities': 1.2,
  'Asset class Japan Equity': 1.1,
  'Asset class Emerging Market Equity': 0.8,
  'Asset class UK Equity': 0.5,
  'Top 10 holdings Cash': 53.1,
  'Top 10 holdings Bond': 2.2,
  'Asset class Global Equity': 34.3,
  'Asset class Investment Grade Bonds': 28.4,
  'Asset class Government bonds': 14.3,
  'Asset class UK Equity': 10.6,
  'Asset class Europe Equity': 2.9,
  'Asset  class Derivatives': 2.0,
  'Asset class Emerging Market Equity': 1.8,
  'Asset class Japan Equity': 1.7,
  'Asset class Emerging Market Debt Bonds': 1.4,
  'Asset class USA Equity': 1.2,
  'Asset class Commodities': 0.8,
  'Asset class Liquid Assets': 0.4,
  'Asset class Stock': 97.2,
  'Asset class Cash': 2.1,
  'Asset class Other': 0.7,
  'Asset class Preferred': 0.0,
  'Asset class Bond': 0.0,
  'Asset class Convertible': 0.0,
  'Region Developed country': 67.1,
  'Region Emerging Market': 29.9,
  'Region United States': 26.8,
  'Region Asia - Emerging': 21.8,
  'Region Asia - Developed': 12.8,
  'Region United Kingdom': 11.6,
  'Region Eurozone': 5.7,
  'Region Japan': 4.1,
  'Region Latin America': 4.1,
  'Region Middle East': 3.3,
  'Region Europe - ex euro': 3.2,
  'Region Africa': 1.4,
  'Region Other': 2.3,
  'Sector Technology': 18.9,
  'Sector Financial services': 17.4,
  'Sector Consumer cyclical': 11.4,
  'Sector Industrials': 9.2,
  'Sector Healthcare': 8.6,
  'Sector Communication Services': 7.8,
  'Sector Consumer defensive': 7.6,
  'Sector Basic materials': 6.2,
  'Sector Energy': 5.3,
  'Sector Utilities': 2.7,
  'Sector Cash & equivalents': 2.1,
  'Sector Real estate': 2.0,
  'Sector Other': 0.0,
  'Top 5 holdings Other': 8.6,
  'Asset class Bond': 56.7,
  'Asset class Cash': 26.8,
  'Asset class Stock': 15.9,
  'Asset class Other': 0.4,
  'Asset class Convertible': 0.1,
  'Asset class Preferred': 0.0,
  'Region Developed country': 15.0,
  'Region United States': 7.0,
  'Region United Kingdom': 3.3,
  'Region Eurozone': 1.6,
  'Region Japan': 1.3,
  'Region Europe - ex euro': 0.9,
  'Region Emerging Market': 0.8,
  'Region Asia - Developed': 0.6,
  'Region Asia - Emerging': 0.6,
  'Region Canada': 0.2,
  'Region Australasia': 0.2,
  'Region Latin America': 0.1,
  'Region Other': 0.2,
  'Top 10 holdings Cash': 2.0,
  'Top 10 holdings Other': 2.0,
  'Sector Government': 36.3,
  'Sector Cash & equivalents': 22.2,
  'Sector Corporate': 21.4,
  'Sector Securitized': 3.6,
  'Sector Technology': 2.4,
  'Sector Real estate': 2.3,
  'Sector Financial services': 2.1,
  'Sector Healthcare': 1.7,
  'Sector Industrials': 1.6,
  'Sector Consumer cyclical': 1.5,
  'Sector Consumer defensive': 1.3,
  'Sector Communication Services': 0.9,
  'Sector Other': 2.0,
  'Asset class Bond': 65.6,
  'Asset class Stock': 26.6,
  'Asset class Cash': 7.2,
  'Asset class Other': 0.6,
  'Asset class Convertible': 0.1,
  'Asset class Preferred': 0.0,
  'Region Developed country': 25.1,
  'Region United States': 11.9,
  'Region United Kingdom': 5.4,
  'Region Eurozone': 2.6,
  'Region Japan': 2.1,
  'Region Europe - ex euro': 1.5,
  'Region Emerging Market': 1.3,
  'Region Asia - Emerging': 1.0,
  'Region Asia - Developed': 1.0,
  'Region Canada': 0.3,
  'Region Australasia': 0.3,
  'Region Latin America': 0.2,
  'Region Other': 0.3,
  'Top 10 holdings Cash': 2.0,
  'Top 10 holdings Other': 3.4,
  'Sector Government': 35.8,
  'Sector Corporate': 29.9,
  'Sector Cash & equivalents': 6.2,
  'Sector Technology': 4.2,
  'Sector Financial services': 3.7,
  'Sector Real estate': 3.1,
  'Sector Healthcare': 2.9,
  'Sector Industrials': 2.8,
  'Sector Consumer cyclical': 2.6,
  'Sector Consumer defensive': 2.2,
  'Sector Communication Services': 1.5,
  'Sector Energy': 1.4,
  'Sector Other': 2.9,
  'Asset class Bond': 51.9,
  'Asset class Stock': 43.5,
  'Asset class Cash': 3.8,
  'Asset class Other': 0.8,
  'Asset class Convertible': 0.1,
  'Asset class Preferred': 0.0,
  'Region Developed country': 41.0,
  'Region United States': 19.7,
  'Region United Kingdom': 8.8,
  'Region Eurozone': 4.3,
  'Region Japan': 3.3,
  'Region Europe - ex euro': 2.5,
  'Region Emerging Market': 2.3,
  'Region Asia - Emerging': 1.6,
  'Region Asia - Developed': 1.4,
  'Region Canada': 0.5,
  'Region Australasia': 0.4,
  'Region Latin America': 0.3,
  'Region Other': 0.4,
  'Top 10 holdings Other': 4.0,
  'Sector Corporate': 26.7,
  'Sector Government': 25.3,
  'Sector Technology': 7.1,
  'Sector Financial services': 6.2,
  'Sector Healthcare': 4.9,
  'Sector Industrials': 4.7,
  'Sector Consumer cyclical': 4.5,
  'Sector Real estate': 3.8,
  'Sector Consumer defensive': 3.8,
  'Sector Cash & equivalents': 3.4,
  'Sector Communication Services': 2.6,
  'Sector Energy': 2.3,
  'Sector Other': 3.7,
  'Asset class Stock': 52.9,
  'Asset class Bond': 42.9,
  'Asset class Cash': 3.3,
  'Asset class Other': 0.8,
  'Asset class Convertible': 0.1,
  'Asset class Preferred': 0.0,
  'Region Developed country': 49.4,
  'Region United States': 23.7,
  'Region United Kingdom': 10.7,
  'Region Eurozone': 5.1,
  'Region Japan': 4.0,
  'Region Emerging Market': 3.2,
  'Region Europe - ex euro': 2.9,
  'Region Asia - Emerging': 2.3,
  'Region Asia - Developed': 1.9,
  'Region Canada': 0.6,
  'Region Latin America': 0.4,
  'Region Australasia': 0.4,
  'Region Other': 0.6,
  'Top 10 holdings Other': 3.4,
  'Sector  Corporate': 25.6,
  'Sector Government': 17.3,
  'Sector Technology': 8.8,
  'Sector Financial services': 7.6,
  'Sector Healthcare': 6.0,
  'Sector Industrials': 5.7,
  'Sector Consumer cyclical': 5.5,
  'Sector Consumer defensive': 4.6,
  'Sector Real estate': 4.0,
  'Sector Communication Services': 3.3,
  'Sector Cash & equivalents': 3.0,
  'Sector Energy': 2.8,
  'Sector Other': 4.4,
  'Asset class Stock': 66.7,
  'Asset class Bond': 30.3,
  'Asset class Cash': 2.0,
  'Asset class Other': 0.9,
  'Asset class Convertible': 0.0,
  'Asset class Preferred': 0.0,
  'Region Developed country': 61.5,
  'Region United States': 29.6,
  'Region United Kingdom': 13.1,
  'Region Eurozone': 6.2,
  'Region Emerging Market': 4.9,
  'Region Japan': 4.8,
  'Region Europe - ex euro': 3.6,
  'Region Asia - Emerging': 3.5,
  'Region Asia - Developed': 2.6,
  'Region Canada': 0.7,
  'Region Latin America': 0.7,
  'Region Middle East': 0.6,
  'Region Other': 0.9,
  'Top 10 holdings Cash': 2.0,
  'Sector Corporate': 19.1,
  'Sector Technology': 11.5,
  'Sector Government': 11.2,
  'Sector Financial services': 9.8,
  'Sector Healthcare': 7.6,
  'Sector Industrials': 7.2,
  'Sector Consumer cyclical': 7.1,
  'Sector Consumer defensive': 5.8,
  'Sector Communication Services': 4.3,
  'Sector Real estate': 4.1,
  'Sector Energy': 3.6,
  'Sector Basic materials': 3.5,
  'Sector Other': 3.9,
  'Asset class Stock': 78.0,
  'Asset class Bond': 19.1,
  'Asset class Cash': 2.0,
  'Asset class Other': 0.9,
  'Asset class Preferred': 0.0,
  'Asset class Convertible': 0.0,
  'Region Developed country': 70.8,
  'Region United States': 33.9,
  'Region United Kingdom': 15.0,
  'Region Eurozone': 7.1,
  'Region Emerging Market': 6.8,
  'Region Japan': 5.5,
  'Region Asia - Emerging': 4.9,
  'Region Europe - ex euro': 4.1,
  'Region Asia - Developed': 3.4,
  'Region Latin America': 0.9,
  'Region Canada': 0.8,
  'Region Middle East': 0.8,
  'Region Other': 1.1,
  'Top 10 holdings Cash': 2.0,
  'Sector Technology': 13.6,
  'Sector Corporate': 11.8,
  'Sector Financial services': 11.7,
  'Sector Healthcare': 8.8,
  'Sector Industrials': 8.4,
  'Sector Consumer cyclical': 8.4,
  'Sector Government': 7.3,
  'Sector Consumer defensive': 6.8,
  'Sector Communication Services': 5.1,
  'Sector Energy': 4.2,
  'Sector Basic materials': 4.1,
  'Sector Real estate': 4.1,
  'Sector Other': 4.2,
  'Asset class Stock': 89.7,
  'Asset class Bond': 7.4,
  'Asset class Cash': 1.9,
  'Asset class Other': 1.0,
  'Asset class Preferred': 0.0,
  'Asset class Convertible': 0.0,
  'Region Developed country': 79.5,
  'Region United States': 37.7,
  'Region United Kingdom': 16.6,
  'Region Emerging Market': 9.7,
  'Region Eurozone': 7.9,
  'Region Asia - Emerging': 7.1,
  'Region Japan': 6.0,
  'Region Asia - Developed': 4.6,
  'Region Europe - ex euro': 4.6,
  'Region Latin America': 1.3,
  'Region Middle East': 1.1,
  'Region Canada': 0.9,
  'Region Other': 1.4,
  'Top 10 holdings Cash': 1.9,
  'Sector Technology': 15.9,
  'Sector Financial services': 13.8,
  'Sector Healthcare': 9.9,
  'Sector Consumer cyclical': 9.7,
  'Sector Industrials': 9.6,
  'Sector Consumer defensive': 7.8,
  'Sector Communication Services': 6.0,
  'Sector Energy': 4.9,
  'Sector Basic materials': 4.9,
  'Sector Real estate': 4.2,
  'Sector Government': 3.9,
  'Sector Corporate': 3.5,
  'Sector Other': 4.4,
  'Asset class Stock': 96.9,
  'Asset class Cash': 2.2,
  'Asset class Other': 0.9,
  'Asset class Preferred': 0.0,
  'Asset class Bond': 0.0,
  'Asset class Convertible': 0.0,
  'Region Developed country': 79.4,
  'Region United States': 36.3,
  'Region Emerging Market': 17.3,
  'Region United Kingdom': 15.8,
  'Region Asia - Emerging': 12.6,
  'Region Asia - Developed': 7.5,
  'Region Eurozone': 7.5,
  'Region Japan': 5.6,
  'Region Europe - ex euro': 4.3,
  'Region Latin America': 2.4,
  'Region Middle East': 1.9,
  'Region Canada': 1.0,
  'Region Other': 1.9,
  'Sector Technology': 18.3,
  'Sector Financial services': 15.9,
  'Sector Consumer cyclical': 11.0,
  'Sector Healthcare': 10.3,
  'Sector Industrials': 10.1,
  'Sector Consumer defensive': 8.3,
  'Sector Communication Services': 7.1,
  'Sector Basic materials': 5.6,
  'Sector Energy': 5.3,
  'Sector Utilities': 2.8,
  'Sector Cash & equivalents': 2.2,
  'Sector Real estate': 2.0,
  'Sector Other': 0.1,
  'Top 5 holdings Other': 13.0,
  'Asset class Bond': 56.4,
  'Asset class Stock': 25.3,
  'Asset class Cash': 12.4,
  'Asset class Other': 5.3,
  'Asset class Convertible': 0.7,
  'Asset class Preferred': 0.0,
  'Region Developed country': 23.7,
  'Region United States': 13.0,
  'Region Eurozone': 3.9,
  'Region United Kingdom': 2.5,
  'Region Japan': 1.5,
  'Region Emerging Market': 1.5,
  'Region Europe - ex euro': 1.4,
  'Region Asia - Emerging': 1.4,
  'Region Asia - Developed': 0.8,
  'Region Australasia': 0.3,
  'Region Canada': 0.3,
  'Region Latin America': 0.1,
  'Region Other': 0.0,
  'Sector Government': 39.8,
  'Sector Corporate': 16.7,
  'Sector Cash & equivalents': 9.1,
  'Sector Industrials': 5.6,
  'Sector Technology': 5.1,
  'Sector Real estate': 2.8,
  'Sector Securitized': 2.7,
  'Sector Financial services': 2.6,
  'Sector Healthcare': 2.3,
  'Sector Communication Services': 2.0,
  'Sector Consumer cyclical': 1.9,
  'Sector Utilities': 1.4,
  'Sector Other': 3.8,
  'Top 10 holdings Other': 23.2,
  'Asset class Bond': 42.3,
  'Asset class Stock': 41.9,
  'Asset class Cash': 8.8,
  'Asset class Other': 6.2,
  'Asset class Convertible': 0.7,
  'Asset class Preferred': 0.0,
  'Region Developed country': 38.2,
  'Region United States': 20.5,
  'Region Eurozone': 6.4,
  'Region United Kingdom': 4.0,
  'Region Emerging Market': 3.5,
  'Region Asia - Emerging': 3.0,
  'Region Europe - ex euro': 2.4,
  'Region Japan': 2.4,
  'Region Asia - Developed': 1.8,
  'Region Australasia': 0.5,
  'Region Canada': 0.3,
  'Region Latin America': 0.3,
  'Region Other': 0.2,
  'Sector Government': 28.8,
  'Sector Corporate': 14.1,
  'Sector Industrials': 9.1,
  'Sector Technology': 8.7,
  'Sector Cash & equivalents': 6.3,
  'Sector Financial services': 4.6,
  'Sector Healthcare': 3.9,
  'Sector Communication Services': 3.4,
  'Sector Consumer cyclical': 3.4,
  'Sector Real estate': 3.3,
  'Sector Utilities': 2.1,
  'Sector Basic materials': 2.0,
  'Sector Other': 5.4,
  'Top 10 holdings Other': 27.2,
  'Asset class Stock': 51.2,
  'Asset class Bond': 33.8,
  'Asset class Cash': 8.1,
  'Asset class Other': 6.2,
  'Asset class Convertible': 0.7,
  'Asset class Preferred': 0.0,
  'Region Developed country': 46.3,
  'Region United States': 24.7,
  'Region Eurozone': 7.7,
  'Region United Kingdom': 4.8,
  'Region Emerging Market': 4.7,
  'Region Asia - Emerging': 4.0,
  'Region Europe - ex euro': 2.9,
  'Region Japan': 2.9,
  'Region Asia - Developed': 2.4,
  'Region Australasia': 0.5,
  'Region Latin America': 0.4,
  'Region Canada': 0.4,
  'Region Other': 0.3,
  'Sector Government': 21.1,
  'Sector Corporate': 13.4,
  'Sector Industrials': 11.1,
  'Sector Technology': 10.8,
  'Sector Financial services': 5.8,
  'Sector Cash & equivalents': 5.5,
  'Sector Healthcare': 4.8,
  'Sector Consumer cyclical': 4.3,
  'Sector Communication Services': 4.3,
  'Sector Real estate': 3.4,
  'Sector Basic materials': 2.5,
  'Sector Utilities': 2.5,
  'Sector Other': 5.8,
  'Top 10 holdings Other': 28.4,
  'Asset class Stock': 64.9,
  'Asset class Bond': 22.2,
  'Asset class Cash': 6.4,
  'Asset class Other': 5.9,
  'Asset class Convertible': 0.7,
  'Asset class Preferred': 0.0,
  'Region Developed country': 58.4,
  'Region United States': 31.0,
  'Region Eurozone': 9.8,
  'Region Emerging Market': 6.3,
  'Region United Kingdom': 6.0,
  'Region Asia - Emerging': 5.4,
  'Region Europe - ex euro': 3.7,
  'Region Japan': 3.6,
  'Region Asia - Developed': 3.2,
  'Region Australasia': 0.6,
  'Region Latin America': 0.6,
  'Region Canada': 0.4,
  'Region Other': 0.4,
  'Sector Industrials': 14.2,
  'Sector Technology': 14.0,
  'Sector Government': 13.8,
  'Sector Corporate': 9.3,
  'Sector Financial services': 7.4,
  'Sector Healthcare': 6.2,
  'Sector Consumer cyclical': 5.5,
  'Sector Communication Services': 5.5,
  'Sector Cash & equivalents': 4.5,
  'Sector Real estate': 3.3,
  'Sector Basic materials': 3.2,
  'Sector Utilities': 3.0,
  'Sector Other': 5.6,
  'Top 10 holdings Other': 25.5,
  'Asset class Stock': 76.1,
  'Asset class Bond': 12.1,
  'Asset class Cash': 5.9,
  'Asset class Other': 5.3,
  'Asset class Convertible': 0.6,
  'Asset class Preferred': 0.0,
  'Region Developed country': 67.8,
  'Region United States': 35.6,
  'Region Eurozone': 11.4,
  'Region Emerging Market': 8.1,
  'Region United Kingdom': 6.9,
  'Region Asia - Emerging': 6.9,
  'Region Europe - ex euro': 4.4,
  'Region Japan': 4.2,
  'Region Asia - Developed': 4.1,
  'Region Latin America': 0.8,
  'Region Australasia': 0.7,
  'Region Canada': 0.4,
  'Region Other': 0.6,
  'Sector Technology': 16.6,
  'Sector Industrials': 16.5,
  'Sector Financial services': 8.9,
  'Sector Government': 8.5,
  'Sector Healthcare': 7.2,
  'Sector Consumer cyclical': 6.6,
  'Sector Communication Services': 6.5,
  'Sector Corporate': 4.8,
  'Sector Cash & equivalents': 4.6,
  'Sector Basic materials': 3.7,
  'Sector Utilities': 3.4,
  'Sector Real estate': 3.2,
  'Sector Other': 5.3,
  'Top 10 holdings Other': 23.9,
  'Asset class Stock': 88.0,
  'Asset class Cash': 5.1,
  'Asset class Bond': 3.3,
  'Asset class Other': 3.3,
  'Asset class Convertible': 0.4,
  'Region Developed country': 77.1,
  'Region United States': 40.0,
  'Region Eurozone': 12.9,
  'Region Emerging Market': 10.7,
  'Region Asia - Emerging': 8.9,
  'Region United Kingdom': 7.7,
  'Region Asia - Developed': 5.5,
  'Region Europe - ex euro': 5.0,
  'Region Japan': 4.8,
  'Region Latin America': 1.2,
  'Region Australasia': 0.7,
  'Region Canada': 0.4,
  'Region Other': 0.8,
  'Sector Technology': 19.4,
  'Sector Industrials': 18.7,
  'Sector Financial services': 10.6,
  'Sector Healthcare': 8.3,
  'Sector Consumer cyclical': 7.9,
  'Sector Communication Services': 7.5,
  'Sector Cash & equivalents': 4.6,
  'Sector Basic materials': 4.2,
  'Sector Utilities': 3.7,
  'Sector Government': 3.7,
  'Sector Consumer defensive': 3.5,
  'Sector Real estate': 3.1,
  'Sector Other': 2.4,
  'Top 10 holdings Other': 13.5
}