







import re

from PyPDF2 import PdfReader


text = [
  'Balanced Attenborough',
  '31 Jul 2023',
  'ASSET CLASS PORTFOLIO CHARACTERISTICS',
  'Benchmark PIMFA EQUITY RISK 3 (NET)',
  'Annualised Benchmark Volatility 8.17%',
  'Annualised Portfolio Volatility 8.23%',
  'Ongoing Costs* 0.69%',
  'Total Number of Holdings (ex cash) 27',
  'Equity 50.70% Fixed Income 19.60%',
  'Multi Asset 14.70% Cash 10.30%',
  'Alternatives 4.70%',
  'OBJECTIVES AND POLICY TOP 10 HOLDINGS BY WEIGHT %',
  'This blend aims to balance protecting capital and generating growth',
  'EdenTree Responsible & Sustainable Short Dated Bond B 9.20%',
  'over the long-term using a combination of assets. There is  a moderate',
  'risk to capital. Royal London Short Term Money Market Y Acc 8.30%',
  'The funds in this model meet the minimum criteria of sustainability as TROJAN ETHICAL FND X GBP ACC 7.00%',
  'laid out in our Sustainability Policy.',
  'VONTOBEL-24 SUS S/T Bond Inc G 6.70%',
  'The Asset Allocation framework governs how Trust DFM combine',
  'BMO RESPONSIBLE UK EQ 2 ACC 6.30%',
  'different asset classes, regions and manager styles to optimise',
  'expected returns, but reduce risk. Royal London Sustainable Leaders Trust C Inc 5.70%',
  'Schroder Global Sust Value Eq I Acc 5.00%',
  'The current economic and political environment is factored into the',
  'portfolio through the quarterly tactical asset allocation. Portfolios are',
  'FP FORESIGHT UK INFRA INC-AA 4.70%',
  'not automatically rebalanced; we review and adjust as deemed',
  'necessary four times each year following our asset allocation process, Jupiter Ecology I Acc 4.70%',
  'and also in exceptional circumstances.',
  'Stewart Investors Asia Pacific Leaders Sustainability Fund',
  '4.30%',
  'There can be no guarantees. The value of Investments may go up and B Acc GBP',
  'down and you may get back less than you invested originally.',
  'PORTFOLIO PERFORMANCE',
  'Time Period** 1m 3m 6m 1yr Inception***',
  'Balanced Attenborough 1.37% 0.64% 0.67% 1.03% 7.25%',
  'PIMFA EQUITY RISK 3 (NET) 2.19% 1.42% 2.43% 1.65% 16.46%',
  '**Cumulative returns',
  '***Inception date: 28 Oct 2020',
  '1 of 4Balanced Attenborough',
  '31 Jul 2023',
  'WEIGHTS BY ASSET',
  'Fixed Income Multi Asset 1.70%',
  'Credit',
  'European Equities 4.00%',
  'Asia Pacific Ex Japan Equities 4.30%',
  'Alternatives 4.70%',
  'Cash 10.30%',
  'UK Equities 11.00%',
  'Global Multi Asset 14.70%',
  'Corporate Bonds 17.90%',
  'Global Equities 31.40%',
  '0% 10% 20% 30% 40%',
  'TOP 10 PERFORMANCE CONTRIBUTORS OVER 1 YEAR 1 Aug 2022 - 31 Jul 2023',
  'Investment Contribution',
  'EdenTree Responsible and Sustainable European Equity B 0.62%',
  'Schroder Global Sust Equity Value Z Acc 0.50%',
  'Royal London Short Term Money Market Fund 0.32%',
  'Jupiter Ecology Fund 0.32%',
  'Schroder Core UK Equity Fund 0.29%',
  'Royal London Sustainable Leaders Trust 0.24%',
  'Blackrock Global Funds-Circular Economy Fund 0.19%',
  'BMO Responsible UK Equity 0.10%',
  'Vontobel Fund-Twentyfour Sustainable Short Term Bond Income 0.09%',
  'Baillie Gifford Global Stewardship Fund 0.08%',
  '2 of 4Balanced Attenborough',
  '31 Jul 2023',
  'GROWTH - OVER 1 YEAR',
  'Balanced Attenborough PIMFA EQUITY RISK 3 (NET)',
  '1 Aug 2022 - 31 Jul 2023',
  '104',
  '102',
  '100',
  ')%( 98',
  'htworG)%(',
  '96',
  '94',
  '92',
  '90',
  'Sep Oct Nov Dec  Jan Feb Mar Apr May Jun Jul',
  '2023',
  '1 Aug 31 Jul',
  '2022 2023',
  'GROWTH - FROM INCEPTION 28 Oct 2020 - 31 Jul 2023',
  '125',
  'Launch date',
  '2021-08-31',
  '120',
  '115',
  'htworG 110',
  '105',
  '100',
  '95',
  'Jan Apr Jul Oct Jan Apr Jul Oct Jan Apr Jul',
  '2021 2022 2023',
  '28 Oct 31 Jul',
  '2020 2023',
  'The  value of investments and the income from them can go down as well as up and past performance is not a guide to future',
  'performance.',
  '3 of 4Balanced  Attenborough',
  '31 Jul 2023',
  'TARGET MARKET DISCLAIMER',
  'The Attenborough range is designed for investors where addressing environmental and social challenges is an important consideration. The',
  'product is suitable for retail investors and professional investors.',
  'This portfolio is suitable for investors who are not first time investors with a basic knowledge and experience of investing who have a need for',
  'capital growth and preservation as well as income generation. This portfolio is suitable for those with a moderate tolerance for market fluctuations.',
  'This portfolio is not suitable for individuals who: require full capital protection; are seeking full repayment of investments; are fully risk averse',
  'and/or with a short investment horizon. There may be some risk to capital.',
  'Our investment approach is a long term one which means we may not be suitable for those investors who wish to invest for less than 3 years, but',
  'we believe that our defined investment process with clear parameters for each of our risk mapped model portfolios  will go some way to reducing',
  'the risks associated with investing when used over a 5-10 year period of time.',
  'The composition of this portfolio may  be subject to change dependent on the platform or wrap provider used, however this does not change the',
  'overall risk rating and therefore associated target market . The information contained in this documentation has been taken from sources stated',
  'and is believed to be reliable and accurate, no information in this document constitutes financial advice.',
  '© 2023 Trust DFM All Rights Reserved.',
  'Portfolio returns in this documentation are calculated using the same share classes of the underlying portfolio constituents from the Advanced',
  'Investment Strategy, or a suitable alternative share class where historic data is not available. The strategy was run by Wills & Trusts IFP Ltd until',
  'September 2018 when management of the Advanced Investment Strategy was delegated to Trust DFM. With all income being reinvested, real',
  'portfolio performance may vary from actual portfolio performance. Past performance is not a guide to future performance and may not be',
  'repeated. The value of investments and the income from them may go down as well as up  and investors may not get back the amounts originally',
  'invested. The investment or investment service may not be suitable for all recipients of this publication and if you have any doubts regarding this,',
  'you should contact your Financial Adviser. Historical performance included in this document prior to the launch date of 31st August 2021 is based',
  'on back testing. Back testing is the process of evaluating an investment strategy by applying it to historical data to simulate what the',
  'performance of such strategy would have been. Back tested performance is purely hypothetical and is provided in this document solely for',
  'informational purposes. Back tested data does not represent actual performance and should not be interpreted as an indication of actual or future',
  'performance. Unlike an actual performance record, hypothetical back-tested performance results do not represent actual trading. In addition, it',
  'does not involve or take into account that material and market factors may have impacted our decision making, all of which can directly affect',
  'actual trading results and performance. *The ongoing cost figures in this documentation are calculated by Trust DFM using the weighted value of',
  'the ongoing costs, ex ante of the portfolio constituents. Where the ongoing costs ex ante is not available the Ongoing Charge Figure (OCF) is',
  'used, or the Total Expenses Ratio (TER) if the OCF is unavailable. If an underlying instrument has no ongoing costs ex ante or OCF or TER figure,',
  'the portfolio expense cannot be calculated. This report was produced by Collidr Research for Trust DFM using pricing data for portfolio',
  'constituents from Bloomberg. Collidr Research is a trading name of Collidr Technologies Limited, registered in England and Wales with company',
  'no. 09061794 at 34  Southwark Bridge Road, London, SE1 9EU. The information contained in this documentation has been taken from sources',
  'stated and is believed to be reliable and accurate, no information in this document constitutes financial advice.For more information, please',
  'contact your Financial Adviser. WTDFM Ltd trading as Trust DFM is authorised and regulated by the Financial Conduct Authority. FRN 782810.',
  'Registered in England and Wales: Company Number 10569496. 91-92 High Street, Thame, OXON OX9 3EH',
  '4 of 4Cultivate Attenborough',
  '31 Jul 2023',
  'ASSET CLASS PORTFOLIO CHARACTERISTICS',
  'Benchmark PIMFA EQUITY RISK 3 (NET)',
  'Annualised Benchmark Volatility 8.17%',
  'Annualised Portfolio Volatility 9.96%',
  'Ongoing Costs* 0.70%',
  'Total Number of Holdings (ex cash) 24',
  'Equity 58.00% Fixed Income 16.70%',
  'Multi Asset 11.30% Cash 9.50%',
  'Alternatives 4.50%',
  'OBJECTIVES AND POLICY TOP 10 HOLDINGS BY WEIGHT %',
  'This blend aims to provide capital growth over the long-term while still',
  'EdenTree Responsible & Sustainable Short Dated Bond B 9.20%',
  'providing some protective elements to capital using a combination of',
  'assets. There is a risk of frequent fluctuations in capital values. Royal London Short Term Money Market Y Acc 7.50%',
  'The funds in this model meet the minimum criteria of sustainability as VONTOBEL-24 SUS S/T Bond Inc G 7.50%',
  'laid out in our Sustainability Policy.',
  'TROJAN ETHICAL FND X GBP ACC 6.80%',
  'The Asset Allocation framework governs how Trust DFM combine',
  'BMO RESPONSIBLE UK EQ 2 ACC 6.80%',
  'different asset classes, regions and manager styles to optimise',
  'expected returns, but reduce risk. Royal London Sustainable Leaders Trust C Inc 6.50%',
  'Schroder Sustainable UK Equity Z Acc 5.80%',
  'The current economic and political environment is factored into the',
  'portfolio through the quarterly tactical asset allocation. Portfolios are',
  'Stewart Investors Asia Pacific Leaders Sustainability Fund',
  'not automatically rebalanced; we review and adjust as deemed 5.80%',
  'B Acc GBP',
  'necessary four times each year following our asset allocation process,',
  'and also in exceptional circumstances. Schroder Global Sust Value Eq I Acc 5.00%',
  'There can be no guarantees. The value of Investments may go up and Jupiter Ecology I Acc 4.80%',
  'down and you may get back less than you invested originally.',
  'PORTFOLIO PERFORMANCE',
  'Time Period** 1m 3m 6m 1yr Inception***',
  'Cultivate Attenborough 1.4% 0.9% 0.98% 1.52% 6.98%',
  'PIMFA EQUITY RISK 3 (NET) 2.19% 1.42% 2.43% 1.65% 16.46%',
  '**Cumulative returns',
  '***Inception date: 28 Oct 2020',
  '1 of 4Cultivate Attenborough',
  '31 Jul 2023',
  'WEIGHTS BY ASSET',
  'Alternatives 4.50%',
  'European Equities 5.00%',
  'Asia Pacific Ex Japan Equities 5.80%',
  'Cash 9.50%',
  'Global Multi Asset 11.30%',
  'UK Equities 13.40%',
  'Corporate Bonds 16.70%',
  'Global Equities 33.80%',
  '0% 10% 20% 30% 40%',
  'TOP 10 PERFORMANCE CONTRIBUTORS OVER 1 YEAR 1 Aug 2022 - 31 Jul 2023',
  'Investment Contribution',
  'EdenTree Responsible and Sustainable European Equity B 0.81%',
  'Schroder Global Sust Equity Value Z Acc 0.48%',
  'Schroder Core UK Equity Fund 0.45%',
  'Royal London Sustainable Leaders Trust 0.36%',
  'Jupiter Ecology Fund 0.33%',
  'Royal London Short Term Money Market Fund 0.26%',
  'Blackrock Global Funds-Circular Economy Fund 0.17%',
  'Lombard Odier Funds-Climate Transition 0.14%',
  'BMO Responsible UK Equity 0.12%',
  'Vontobel Fund-Twentyfour Sustainable Short Term Bond Income 0.09%',
  '2 of 4Cultivate Attenborough',
  '31 Jul 2023',
  'GROWTH - OVER 1 YEAR',
  'Cultivate Attenborough PIMFA EQUITY RISK 3 (NET)',
  '1 Aug 2022 - 31 Jul 2023',
  '104',
  '102',
  '100',
  ')%( 98',
  'htworG)%(',
  '96',
  '94',
  '92',
  '90',
  'Sep Oct Nov Dec Jan Feb Mar Apr May Jun Jul',
  '2023',
  '1 Aug 31 Jul',
  '2022 2023',
  'GROWTH - FROM  INCEPTION 28 Oct 2020 - 31 Jul 2023',
  '125',
  '120',
  '115',
  'htworG 110',
  '105',
  '100',
  '95',
  'Jan Apr Jul Oct Jan Apr Jul Oct Jan Apr Jul',
  '2021 2022 2023',
  '28 Oct 31 Jul',
  '2020 2023',
  'The value of investments and the income from them can go down as well as up and past performance is not a guide to  future',
  'performance.',
  '3 of 4Cultivate Attenborough',
  '31 Jul 2023',
  'TARGET MARKET DISCLAIMER',
  'The Attenborough range is designed for investors where addressing environmental and social challenges is an important consideration. The',
  'product is suitable for retail investors and professional investors.',
  'This portfolio is suitable for investors with a good understanding of factors that drive stock price movements and how those movements might',
  'impact the value of the portfolio. Investors should also have previous experience in investing and are able to understand the benefits of',
  'diversification and limited downside protection. This portfolio is suitable for those with a mid-high tolerance for market fluctuations.',
  'This portfolio is not  suitable for individuals who: require full capital protection; are seeking full repayment of investments; are fully risk averse',
  'and/or with a short investment horizon. There may be some risk to capital.',
  'Our investment approach is a long term one which means we may not be suitable for those investors who wish to invest for less than 3 years, but',
  'we believe that our defined investment process with clear parameters for each of our risk mapped model portfolios will go some way to reducing',
  'the risks associated with investing when used over a 5-10 year period of time.',
  'The composition of this  portfolio may be subject to change dependent on the platform or wrap provider used, however this does not change the',
  'overall risk rating and therefore associated target market . The information contained in this documentation has been taken from sources stated',
  'and is believed to be reliable and accurate, no information in this document constitutes financial advice.',
  '© 2023 Trust DFM All Rights Reserved.',
  'Portfolio returns in this documentation are calculated using the share classes of the underlying portfolio constituents from the Advanced',
  'Investment Strategy. The strategy was run by Wills & Trusts IFP Ltd until September 2018 when management of the Advanced Investment',
  'Strategy was delegated to Trust DFM. With all income being reinvested, real portfolio performance may vary from actual portfolio',
  'performance. Past performance is not a guide to future performance and may not be repeated. The value of investments and the income from',
  'them may go down as well as up and investors may not get back the amounts originally invested. The investment or investment service may not',
  'be suitable for all recipients of this publication and if you have any doubts regarding this, you should contact your Financial Adviser. *The ongoing',
  'cost figures in this documentation are calculated by Trust DFM using the weighted value of the ongoing costs, ex ante of the portfolio',
  'constituents. Where the ongoing costs ex ante is not available the OCF is used. If an underlying instrument has no ongoing costs ex ante or OCF',
  'or TER figure, the portfolio expense cannot be calculated. This report was produced by Collidr Research for Trust DFM using pricing data for',
  'portfolio constituents from Bloomberg. Collidr Research is a trading name of Collidr Technologies Limited, registered in England and  Wales with',
  'company no. 09061794 at 34 Southwark Bridge Road, London, SE1 9EU. The information contained in this documentation has been taken from',
  'sources stated and is believed to be reliable and accurate, no information in this document constitutes financial advice.',
  'For more information, please contact your Financial Adviser.',
  'WTDFM Ltd trading as Trust DFM is authorised and regulated by the Financial Conduct Authority. FRN 782810. Registered in England and Wales',
  'number 10569496. 91-92 High Street, Thame, OXON OX9 3EH',
  '4 of 4Endure Attenborough',
  '31 Jul 2023',
  'ASSET CLASS PORTFOLIO  CHARACTERISTICS',
  'Benchmark PIMFA EQUITY RISK 2 (NET)',
  'Annualised Benchmark Volatility 6.64%',
  'Annualised Portfolio Volatility 6.19%',
  'Ongoing Costs* 0.65%',
  'Total Number of Holdings (ex cash) 20',
  'Equity 31.00% Fixed Income 25.50%',
  'Multi Asset 22.00% Cash 14.50%',
  'Alternatives 7.00%',
  'OBJECTIVES AND POLICY TOP 10 HOLDINGS BY WEIGHT %',
  'This blend aims to balance protecting capital and generating growth',
  'Royal London Short Term Money Market Y Acc 12.50%',
  'over the long-term using a combination of assets. There is moderate',
  'risk to capital. TROJAN ETHICAL FND X GBP ACC 10.50%',
  'The funds in this model meet the minimum criteria of sustainability as VONTOBEL-24 SUS S/T Bond Inc G 10.00%',
  'laid out in our Sustainability Policy.',
  'EdenTree Responsible & Sustainable Short Dated Bond B 10.00%',
  'The Asset Allocation framework governs how Trust DFM combine',
  'FP FORESIGHT UK INFRA INC-AA 7.00%',
  'different asset classes, regions and manager styles to optimise',
  'expected returns, but reduce risk. BMO RESPONSIBLE UK EQ 2 ACC 5.00%',
  'Royal London Sustainable Leaders Trust C Inc 4.50%',
  'The current economic and political environment is factored into the',
  'portfolio through the quarterly tactical asset allocation. Portfolios are',
  'Royal London Sustainable Managed Growth C 4.00%',
  'not automatically rebalanced; we review and adjust as  deemed',
  'necessary four times each year following our asset allocation process, JPM Global Macro Sustainable Fund GBPH C Acc 3.50%',
  'and also in exceptional circumstances.',
  'EdenTree Responsible & Sust Eurp Eq B 3.50%',
  'There can be no guarantees. The value of Investments may go up and',
  'down and you may get back less than you invested originally.',
  'PORTFOLIO PERFORMANCE',
  'Time Period** 1m 3m 6m 1yr Inception***',
  'Endure Attenborough 1.24% -0.21% 0.06% 0.1% 4.97%',
  'PIMFA EQUITY RISK 2 (NET) 2.02% 0.31% 0.88% -1.47% 4.96%',
  '**Cumulative returns',
  '***Inception date: 28 Oct 2020',
  '1 of 4Endure Attenborough',
  '31 Jul 2023',
  'WEIGHTS BY ASSET',
  'Asia Pacific Ex Japan Equities 2.50%',
  'Fixed Income Multi Asset 2.50%',
  'Credit',
  'European Equities 3.50%',
  'Alternatives 7.00%',
  'UK Equities 8.00%',
  'Cash 14.50%',
  'Global Equities 17.00%',
  'Global Multi Asset 22.00%',
  'Corporate Bonds 23.00%',
  '0% 5% 10% 15% 20% 25%',
  'TOP 10 PERFORMANCE CONTRIBUTORS OVER 1 YEAR 1 Aug 2022 - 31 Jul 2023',
  'Investment Contribution',
  'EdenTree Responsible and Sustainable European Equity B 0.66%',
  'Royal London Short Term Money Market Fund 0.49%',
  'Schroder Global Sust Equity Value Z Acc 0.35%',
  'Schroder Core UK  Equity Fund 0.24%',
  'Jupiter Ecology Fund 0.24%',
  'Royal London Sustainable Leaders Trust 0.19%',
  'Vontobel Fund-Twentyfour Sustainable Short Term Bond  Income 0.13%',
  'Blackrock Global Funds-Circular Economy Fund 0.13%',
  'BMO Responsible UK Equity 0.08%',
  'Baillie Gifford Global Stewardship Fund 0.05%',
  '2 of 4Endure Attenborough',
  '31 Jul 2023',
  'GROWTH - OVER 1 YEAR',
  'Endure Attenborough PIMFA EQUITY RISK 2 (NET)',
  '1 Aug 2022 - 31 Jul 2023',
  '102',
  '100',
  '98',
  ')%( 96',
  'htworG)%(',
  '94',
  '92',
  '90',
  '88',
  'Sep Oct Nov Dec Jan Feb Mar Apr May Jun Jul',
  '2023',
  '1 Aug 31 Jul',
  '2022 2023',
  'GROWTH - FROM INCEPTION 28 Oct 2020 - 31 Jul 2023',
  '116',
  'Launch date',
  '2021-08-31',
  '114',
  '112',
  '110',
  '108',
  '106',
  'htworG',
  '104',
  '102',
  '100',
  '98',
  '96',
  '94',
  'Jan Apr Jul Oct Jan Apr Jul Oct Jan Apr Jul',
  '2021 2022 2023',
  '28 Oct 31 Jul',
  '2020 2023',
  'The value of investments and the income from them can go down as well as up and past performance is not a guide to future',
  'performance.',
  '3 of 4Endure Attenborough',
  '31 Jul 2023',
  'TARGET MARKET DISCLAIMER',
  'TThe Attenborough range is designed for investors where addressing environmental and social challenges is an important consideration. The',
  'product is suitable for retail investors and professional investors.',
  'This portfolio is suitable for investors with basic knowledge and experience of investing who have a need for both capital preservation and income.',
  'This portfolio is suitable for those with a low-moderate tolerance for market fluctuations.',
  'This portfolio is not suitable for individuals who: require full capital protection; are seeking full repayment of investments; are fully risk averse',
  'and/or with a short investment horizon. There may be some risk to capital.',
  'Our investment approach is a long term one which means we may not be suitable for those investors who wish to invest for less than 3 years, but',
  'we believe that our defined investment process with clear parameters for each of our risk mapped model portfolios will go some way to',
  'reducingthe risks associated with investing when used over a 5-10 year  period of time.',
  'The composition of this portfolio may be subject to change dependent on the platform or wrap provider used, however this does not change the',
  'overall risk rating and therefore associated target market . The information contained in this documentation has been taken from sources stated',
  'and is believed to be reliable and accurate, no information in this document constitutes financial advice.',
  '© 2023 Trust DFM All Rights Reserved.',
  'Portfolio returns in this documentation are calculated using the same share classes of the underlying portfolio constituents from the Advanced',
  'Investment Strategy, or a suitable alternative share class where historic data is not available. The strategy was run by Wills & Trusts IFP Ltd until',
  'September 2018 when management of the Advanced Investment Strategy was delegated to Trust DFM. With all income being reinvested, real',
  'portfolio performance may vary from actual portfolio performance. Past performance is not a guide to future performance and may not be',
  'repeated. The value of investments and the income from them may go down as well as up and investors may not get back the amounts originally',
  'invested. The investment or investment service may not be suitable for all recipients of this publication and if you have any doubts regarding this,',
  'you should contact your Financial Adviser. Historical performance included in this document prior to the launch date of 31st August 2021 is based',
  'on back testing. Back testing is the process of evaluating an investment strategy by applying it to historical data to simulate what the',
  'performance of such strategy would have been. Back tested performance is purely hypothetical and is provided in this document solely for',
  'informational purposes. Back tested data does not represent actual performance and should not be interpreted as an indication of actual or future',
  'performance. Unlike an actual performance record, hypothetical back-tested performance results do not represent actual trading. In addition, it',
  'does not involve or take into account that material and market factors may have impacted our decision making, all of which can directly affect',
  'actual trading results and performance. *The ongoing cost figures in this documentation are calculated by Trust DFM using the weighted value of',
  'the ongoing costs, ex ante of the portfolio constituents. Where the ongoing costs ex ante is not available the Ongoing Charge Figure (OCF) is',
  'used, or the Total Expenses Ratio (TER) if the OCF is unavailable. If an underlying instrument has no ongoing costs ex ante or OCF or TER figure,',
  'the portfolio expense cannot be calculated. This report was produced by Collidr Research for Trust DFM using pricing data for portfolio',
  'constituents from Bloomberg. Collidr Research is a trading name of Collidr Technologies Limited, registered in England and Wales with company',
  'no. 09061794 at 34 Southwark Bridge Road, London, SE1 9EU. The information contained in this documentation has been taken from sources',
  'stated and is believed to be reliable and accurate, no information in this document constitutes financial advice.For more information, please',
  'contact your Financial Adviser. WTDFM Ltd trading as Trust DFM is authorised and regulated by the Financial Conduct Authority. FRN 782810.',
  'Registered in England and Wales: Company Number 10569496. 91-92 High Street, Thame, OXON OX9 3EH',
  '4 of 4Flourish Attenborough',
  '31 Jul 2023',
  'ASSET CLASS PORTFOLIO CHARACTERISTICS',
  'Benchmark PIMFA EQUITY RISK 4 (NET)',
  'Annualised Benchmark Volatility 9.84%',
  'Annualised Portfolio Volatility 10.35%',
  'Ongoing Costs* 0.73%',
  'Total Number of Holdings (ex cash) 24',
  'Equity 68.50% Fixed Income 14.00%',
  'Multi Asset 7.50% Cash 7.00%',
  'Alternatives 3.00%',
  'OBJECTIVES AND POLICY TOP 10 HOLDINGS BY WEIGHT %',
  'This blend aims to provide capital growth over the long-term while still',
  'EdenTree Responsible & Sustainable Short Dated Bond B 9.00%',
  'providing some protective elements to capital using a combination of',
  'assets. There is a risk  of frequent fluctuations in capital values. BMO RESPONSIBLE UK EQ 2 ACC 7.50%',
  'The funds in this model meet the minimum criteria of sustainability as  Royal London Sustainable Leaders Trust C Inc 7.00%',
  'laid out in our Sustainability Policy.',
  'Stewart Investors Asia Pacific Leaders Sustainability Fund',
  '6.50%',
  'B Acc GBP',
  'The Asset Allocation framework governs how Trust DFM combine',
  'different asset classes, regions and manager styles to optimise',
  'Schroder Global Sust Value Eq I Acc 6.00%',
  'expected returns, but reduce risk.',
  'Schroder Sustainable UK Equity Z Acc 5.50%',
  'The current economic and political environment is factored into the',
  'Jupiter Ecology I Acc 5.50%',
  'portfolio through the quarterly tactical asset allocation. Portfolios are',
  'not automatically rebalanced; we review and adjust as deemed',
  'Royal London Short Term Money Market Y Acc 5.00%',
  'necessary four times each year following our asset allocation process,',
  'and also in exceptional circumstances. VONTOBEL-24 SUS S/T Bond Inc G 5.00%',
  'There can be no guarantees. The value of Investments may go up and BGF CIRCULAR ECONOMY D2 GBP Hdg 4.50%',
  'down and you may get back less than you invested originally.',
  'PORTFOLIO PERFORMANCE',
  'Time Period** 1m 3m 6m 1yr Inception***',
  'Flourish Attenborough 1.47% 1.38% 1.29% 2.09% 10.23%',
  'PIMFA EQUITY RISK 4 (NET) 2.29%  2.47% 3.98% 5.09% 26.96%',
  '**Cumulative returns',
  '***Inception date: 28 Oct 2020',
  '1 of 4Flourish Attenborough',
  '31 Jul 2023',
  'WEIGHTS BY ASSET',
  'Alternatives 3.00%',
  'European Equities 5.00%',
  'Asia Pacific Ex Japan Equities 6.50%',
  'Cash 7.00%',
  'Global Multi Asset 7.50%',
  'Corporate Bonds 14.00%',
  'UK Equities 14.50%',
  'Global Equities 42.50%',
  '0% 10% 20% 30% 40% 50%',
  'TOP 10 PERFORMANCE CONTRIBUTORS OVER 1 YEAR 1 Aug 2022 - 31 Jul 2023',
  'Investment Contribution',
  'EdenTree Responsible and Sustainable European Equity B 0.75%',
  'Schroder Global Sust Equity Value Z Acc 0.60%',
  'Schroder Core UK Equity Fund 0.43%',
  'Jupiter Ecology Fund 0.37%',
  'Royal London Sustainable Leaders Trust 0.30%',
  'Blackrock Global Funds-Circular Economy Fund 0.29%',
  'Royal London Short Term Money Market Fund 0.17%',
  'BMO Responsible UK Equity 0.13%',
  'Baillie Gifford Global Stewardship Fund 0.13%',
  'Regnan Global Equity Impact Solutions/United Kingdom 0.12%',
  '2 of 4Flourish Attenborough',
  '31 Jul 2023',
  'GROWTH - OVER 1 YEAR',
  'Flourish Attenborough PIMFA EQUITY RISK 4 (NET)',
  '1 Aug 2022 - 31 Jul 2023',
  '106',
  '104',
  '102',
  '100',
  ')%(',
  'htworG)%( 98',
  '96',
  '94',
  '92',
  '90',
  'Sep Oct Nov Dec Jan Feb Mar Apr May Jun Jul',
  '2023',
  '1 Aug 31 Jul',
  '2022 2023',
  'GROWTH - FROM INCEPTION 28 Oct 2020 - 31 Jul 2023',
  '130',
  'Launch date',
  '2021-08-31',
  '125',
  '120',
  '115',
  'htworG',
  '110',
  '105',
  '100',
  '95',
  'Jan Apr Jul Oct Jan Apr Jul Oct Jan Apr Jul',
  '2021 2022 2023',
  '28 Oct 31 Jul',
  '2020 2023',
  'The value of investments and the income from them can go down as well as up and past performance is not a guide to future',
  'performance.',
  '3 of 4Flourish Attenborough',
  '31 Jul 2023',
  'TARGET MARKET DISCLAIMER',
  'The Attenborough range is designed for investors where addressing environmental and social challenges is an important consideration. The',
  'product is suitable for retail investors and professional investors.',
  'This portfolio is suitable for investors with a good understanding of factors that drive stock price movements and how those movements might',
  'impact the value of the portfolio. Investors  should also have previous experience in investing and are able to understand the benefits of',
  'diversification and limited downside protection. This portfolio is suitable for those with a mid-high tolerance for market fluctuations.',
  'This portfolio is not suitable for individuals who: require full capital protection; are seeking full repayment of investments; are fully risk averse',
  'and/or with a short investment horizon. There may be some risk to capital.',
  'Our investment approach is a long term one which means we may not be suitable for those investors who wish to invest for less than 3 years, but',
  'we believe that our defined investment process with clear parameters for each of our risk mapped model portfolios will go some way to reducing',
  'the risks associated with investing when used over a 5-10 year period of time.',
  'The composition of this portfolio may be subject to change dependent on the platform or wrap provider used, however this does not change the',
  'overall risk rating and therefore associated target market . The information contained in this documentation has been taken from sources stated',
  'and is believed to be reliable and accurate, no information in this document constitutes financial advice.',
  '© 2023 Trust DFM All Rights Reserved.',
  'Portfolio returns in this documentation are calculated using the same share classes  of the underlying portfolio constituents from the Advanced',
  'Investment Strategy, or a suitable alternative share class where historic data is not available. The strategy was run by Wills & Trusts IFP Ltd until',
  'September 2018 when management of the Advanced Investment Strategy was delegated to Trust DFM. With all income being reinvested, real',
  'portfolio performance may vary from actual portfolio performance. Past performance is not a guide to future performance and may not be',
  'repeated. The value of investments and the income from them may go down as well as up and investors may not get back the amounts originally',
  'invested. The investment or investment service may not be suitable for all recipients of this publication and if you have any doubts regarding this,',
  'you should contact your Financial Adviser. Historical performance included in this document prior to the launch date of 31st August 2021 is based',
  'on back testing. Back testing is the process of evaluating an investment strategy by applying it to historical data to simulate what the',
  'performance of such strategy would have been. Back tested performance is purely hypothetical and is provided in this document solely for',
  'informational purposes. Back tested data does not represent actual performance and should not be interpreted as an indication of actual or future',
  'performance. Unlike an actual performance record, hypothetical back-tested performance results do not represent actual trading. In addition, it',
  'does not involve or take into account that material and market factors may have impacted our decision making, all of which can directly affect',
  'actual trading results and performance. *The ongoing cost figures in this documentation are calculated by Trust DFM using the weighted value of',
  'the ongoing costs, ex ante of the portfolio constituents. Where the ongoing costs ex ante is not available the Ongoing Charge Figure (OCF) is',
  'used, or the Total Expenses  Ratio (TER) if the OCF is unavailable. If an underlying instrument has no ongoing costs ex ante or OCF or TER figure,',
  'the portfolio expense cannot be calculated. This report was produced by Collidr Research for Trust DFM using pricing data for portfolio',
  'constituents from Bloomberg. Collidr Research is a trading name of Collidr Technologies Limited, registered in England and Wales with company',
  'no. 09061794 at 34 Southwark Bridge Road, London, SE1 9EU. The information contained in this documentation has been taken from sources',
  'stated and is believed to be reliable and accurate, no information in this document constitutes financial advice.For more information, please',
  'contact your Financial Adviser. WTDFM Ltd trading as Trust DFM is authorised and regulated by the Financial Conduct Authority. FRN 782810.',
  'Registered in England and Wales: Company Number 10569496. 91-92 High Street, Thame, OXON OX9 3EH',
  '4 of 4Magnify Attenborough',
  '31 Jul 2023',
  'ASSET CLASS PORTFOLIO CHARACTERISTICS',
  'Benchmark PIMFA EQUITY RISK 3 (NET)',
  'Annualised Benchmark Volatility 8.17%',
  'Annualised Portfolio Volatility 12.20%',
  'Ongoing Costs* 0.76%',
  'Total Number of Holdings (ex cash) 24',
  'Equity 79.00% Fixed Income 11.00%',
  'Cash 4.50% Multi Asset 4.00%',
  'Alternatives 1.50%',
  'OBJECTIVES AND POLICY TOP 10 HOLDINGS BY WEIGHT %',
  'This blend aims to provide capital growth over the long-term while still',
  'EdenTree Responsible & Sustainable Short Dated Bond B 8.50%',
  'providing some protective elements to capital using a combination of',
  'assets, but with an emphasis on growth. There is a high risk to capital BMO RESPONSIBLE UK EQ 2 ACC 8.20%',
  'and there can be wide fluctuations in capital values of investments.',
  'Royal London Sustainable Leaders Trust C Inc 7.50%',
  'The funds in this model meet the minimum criteria of sustainability as',
  'Stewart Investors Asia Pacific Leaders Sustainability Fund',
  'laid out in our Sustainability Policy. 7.20%',
  'B Acc GBP',
  'The Asset Allocation framework governs how Trust DFM combine',
  'Schroder Global Sust Value Eq I Acc 7.00%',
  'different asset classes, regions and manager styles to optimise',
  'expected returns, but reduce risk. Jupiter Ecology I Acc 6.20%',
  'Schroder Sustainable UK Equity Z Acc 5.20%',
  'The current economic and political environment is factored into the',
  'portfolio through the quarterly tactical asset allocation. Portfolios are',
  'BMO Responsible Global Equity 2 Acc 5.20%',
  'not automatically rebalanced; we review and adjust as deemed',
  'necessary four times each year following our asset allocation process, BGF CIRCULAR ECONOMY D2 GBP Hdg 4.80%',
  'and also in exceptional circumstances.',
  'Baillie Gifford Global Stewardship B Acc 4.80%',
  'There can be no guarantees. The value of Investments may go up and',
  'down and you may get back less than you invested originally.',
  'PORTFOLIO PERFORMANCE',
  'Time Period** 1m 3m 6m 1yr Inception***',
  'Magnify Attenborough 1.55% 1.84% 1.58% 1.87% 9.16%',
  'PIMFA EQUITY RISK 3 (NET) 2.19% 1.42% 2.43% 1.65% 16.46%',
  '**Cumulative returns',
  '***Inception date: 28 Oct 2020',
  '1 of 4Magnify Attenborough',
  '31 Jul 2023',
  'WEIGHTS BY ASSET',
  'Alternatives 1.50%',
  'Global Multi Asset 4.00%',
  'Cash 4.50%',
  'European Equities 5.00%',
  'Asia Pacific Ex Japan Equities 7.20%',
  'Corporate Bonds 11.00%',
  'UK Equities 15.60%',
  'Global Equities 51.20%',
  '0% 20% 40% 60%',
  'TOP 10 PERFORMANCE CONTRIBUTORS OVER 1 YEAR 1 Aug 2022 - 31 Jul 2023',
  'Investment Contribution',
  'Schroder Global Sust Equity Value Z Acc 0.65%',
  'Royal London Sustainable Leaders Trust 0.57%',
  'EdenTree Responsible and Sustainable European Equity B 0.54%',
  'Jupiter Ecology Fund 0.45%',
  'Schroder Core UK Equity Fund 0.41%',
  'Lombard Odier Funds-Climate Transition 0.24%',
  'Regnan Global Equity Impact Solutions/United Kingdom 0.18%',
  'Regnan UK Umbrella Fund-Regnan Sustainable Water & Waste Fund 0.11%',
  'Royal London Short Term Money Market Fund  0.08%',
  'Trojan Ethical Fund 0.05%',
  '2 of 4Magnify Attenborough',
  '31 Jul 2023',
  'GROWTH - OVER 1 YEAR',
  'Magnify Attenborough PIMFA EQUITY RISK 3 (NET)',
  '1 Aug 2022 - 31 Jul 2023',
  '104',
  '102',
  '100',
  ')%( 98',
  'htworG)%(',
  '96',
  '94',
  '92',
  '90',
  'Sep Oct Nov Dec Jan Feb Mar Apr May Jun Jul',
  '2023',
  '1 Aug 31 Jul',
  '2022 2023',
  'GROWTH - FROM INCEPTION 28 Oct 2020 - 31 Jul 2023',
  '135',
  '130',
  '125',
  '120',
  'htworG 115',
  '110',
  '105',
  '100',
  '95',
  'Jan Apr Jul Oct Jan Apr Jul Oct Jan Apr Jul',
  '2021 2022 2023',
  '28 Oct 31 Jul',
  '2020 2023',
  'The value of investments and the income from them can  go down as well as up and past performance is not a guide to future',
  'performance.',
  '3 of 4Magnify Attenborough',
  '31 Jul 2023',
  'TARGET MARKET DISCLAIMER',
  'The Attenborough range is designed for investors where addressing environmental and social challenges is an important consideration. The',
  'product is suitable for retail investors and professional investors.',
  'This portfolio is suitable for those with a high tolerance for market fluctuations.  You must understand you are taking on a high level of risk and',
  'there could be wide fluctuations in the capital values of your investments. There is a high risk to capital.',
  'This portfolio is not suitable for individuals who: require full capital protection; are seeking full repayment of investments; are fully risk averse',
  'and/or with a short investment horizon. There may be some risk to capital.',
  'Our investment approach is a long term one which means we may not be suitable for those investors who wish to invest for less than 3 years, but',
  'we believe that our defined investment process with  clear parameters for each of our risk mapped model portfolios will go some way to reducing',
  'the risks associated with investing when used over a 5-10  year period of time.',
  'The composition of this portfolio may be subject to change dependent on the platform or wrap provider used, however this does not change the',
  'overall risk rating and therefore associated target market . The information contained in this documentation has been taken from sources stated',
  'and is believed to be reliable and accurate, no information in this document constitutes financial advice.',
  '© 2023 Trust DFM All Rights Reserved.',
  'Portfolio returns in this documentation are calculated using the share classes of the underlying portfolio constituents from the Advanced',
  'Investment Strategy. The strategy was run by Wills & Trusts IFP Ltd until September 2018 when management of the Advanced Investment',
  'Strategy was delegated to Trust DFM. With all income being reinvested, real portfolio performance may vary from actual portfolio',
  'performance. Past performance is not a guide to future performance and may not be repeated. The value of investments and the income from',
  'them may go down as well as up and investors may not get back the amounts originally invested. The investment or investment service may not',
  'be suitable for all recipients of this publication and if you have any doubts regarding this, you should contact your Financial Adviser. *The ongoing',
  'cost figures in this documentation are calculated by Trust DFM using the weighted value of the ongoing costs, ex ante of the portfolio',
  'constituents. Where the ongoing costs ex ante is not available the OCF is used. If an underlying instrument has no ongoing costs ex ante or OCF',
  'or TER figure, the portfolio expense cannot be calculated. This report was produced by Collidr Research for Trust DFM using pricing data for',
  'portfolio constituents from Bloomberg. Collidr Research is a trading name of Collidr  Technologies Limited, registered in England and Wales with',
  'company no. 09061794 at 34 Southwark Bridge Road, London, SE1 9EU. The information contained in this documentation has been taken from',
  'sources stated and is believed to be reliable and accurate, no information in this document constitutes  financial advice.',
  'For more information, please contact your Financial Adviser.',
  'WTDFM Ltd trading as Trust DFM is authorised and regulated by the Financial Conduct Authority. FRN 782810. Registered in England and Wales',
  'number 10569496. 91-92 High Street, Thame, OXON OX9 3EH',
  '4 of 4Mature Attenborough',
  '31 Jul 2023',
  'ASSET CLASS PORTFOLIO CHARACTERISTICS',
  'Benchmark PIMFA EQUITY RISK 2 (NET)',
  'Annualised Benchmark Volatility 6.64%',
  'Annualised Portfolio Volatility 7.19%',
  'Ongoing Costs* 0.66%',
  'Total Number of Holdings (ex cash) 20',
  'Equity 39.00% Fixed Income 22.70%',
  'Multi Asset 18.60% Cash 13.20%',
  'Alternatives 6.50%',
  'OBJECTIVES AND POLICY TOP 10 HOLDINGS BY WEIGHT %',
  'This blend aims to balance protecting capital and generating growth',
  'Royal London Short Term Money Market Y Acc 11.20%',
  'over the long-term using a combination of assets. There is a moderate',
  'risk to capital. VONTOBEL-24 SUS S/T Bond Inc G 10.00%',
  'The funds in this model meet the minimum criteria of sustainability as EdenTree Responsible & Sustainable  Short Dated Bond B 10.00%',
  'laid out in our Sustainability Policy.',
  'TROJAN ETHICAL FND X GBP ACC 9.80%',
  'The Asset Allocation framework governs how  Trust DFM combine',
  'FP FORESIGHT UK INFRA INC-AA 6.50%',
  'different asset classes, regions and manager styles to optimise',
  'expected returns, but reduce risk. BMO RESPONSIBLE UK EQ 2 ACC 5.50%',
  'Royal London Sustainable Leaders Trust C Inc 5.20%',
  'The current economic and political environment is factored into the',
  'portfolio through the quarterly tactical asset allocation. Portfolios are',
  'Schroder Sustainable UK Equity Z Acc 4.50%',
  'not automatically rebalanced; we review and adjust as deemed',
  'necessary four times each year following our asset allocation process, EdenTree Responsible & Sust Eurp Eq B 4.20%',
  'and also in exceptional circumstances.',
  'Schroder Global Sust Value Eq I Acc 3.80%',
  'There can be no guarantees. The value of Investments may go up and',
  'down and you may get back less than you invested originally.',
  'PORTFOLIO PERFORMANCE',
  'Time Period** 1m 3m 6m 1yr Inception***',
  'Mature Attenborough 1.28% 0.11% 0.37% 0.69% 7.14%',
  'PIMFA EQUITY RISK 2 (NET) 2.02% 0.31% 0.88% -1.47% 4.96%',
  '**Cumulative returns',
  '***Inception date: 28 Oct 2020',
  '1 of 4Mature Attenborough',
  '31 Jul 2023',
  'WEIGHTS BY ASSET',
  'Fixed Income Multi Asset 1.20%',
  'Credit',
  'Asia Pacific Ex Japan Equities 3.80%',
  'European Equities 4.20%',
  'Alternatives 6.50%',
  'UK Equities 10.00%',
  'Cash 13.20%',
  'Global Multi Asset 18.60%',
  'Global Equities 21.00%',
  'Corporate Bonds 21.50%',
  '0% 5% 10% 15% 20% 25%',
  'TOP 10 PERFORMANCE CONTRIBUTORS OVER 1 YEAR 1 Aug 2022 - 31 Jul 2023',
  'Investment Contribution',
  'EdenTree Responsible and Sustainable European Equity B 0.79%',
  'Royal London Short Term Money Market Fund 0.41%',
  'Schroder Global Sust Equity Value Z Acc 0.38%',
  'Schroder Core UK Equity Fund 0.35%',
  'Jupiter Ecology Fund 0.25%',
  'Royal London Sustainable Leaders Trust 0.22%',
  'Blackrock Global  Funds-Circular Economy Fund 0.19%',
  'Vontobel Fund-Twentyfour Sustainable Short Term Bond Income 0.13%',
  'BMO Responsible UK Equity 0.09%',
  'Baillie Gifford Global Stewardship Fund 0.08%',
  '2 of 4Mature Attenborough',
  '31 Jul 2023',
  'GROWTH - OVER 1 YEAR',
  'Mature Attenborough PIMFA EQUITY RISK 2 (NET)',
  '1 Aug 2022 - 31 Jul 2023',
  '104',
  '102',
  '100',
  '98',
  ')%(',
  'htworG)%( 96',
  '94',
  '92',
  '90',
  '88',
  'Sep Oct Nov Dec Jan Feb Mar Apr May Jun Jul',
  '2023',
  '1 Aug 31 Jul',
  '2022 2023',
  'GROWTH - FROM INCEPTION 28 Oct 2020 - 31 Jul 2023',
  '120',
  '115',
  '110',
  'htworG 105',
  '100',
  '95',
  '90',
  'Jan Apr  Jul Oct Jan Apr Jul Oct Jan Apr Jul',
  '2021 2022 2023',
  '28 Oct 31 Jul',
  '2020 2023',
  'The value of investments and the income from them can go down as  well as up and past performance is not a guide to future',
  'performance.',
  '3 of 4Mature Attenborough',
  '31 Jul 2023',
  'TARGET MARKET DISCLAIMER',
  'The  Attenborough range is designed for investors where addressing environmental and social challenges is an important consideration. The',
  'product is suitable for retail investors and professional investors.',
  'This portfolio is suitable for investors who are not first time investors with a basicknowledge  and experience of investing who have a need for',
  'capital growth and preservation as well as income generation. This portfolio is suitablefor those with a moderate tolerance for market fluctuations.',
  'This portfolio is not suitable for individuals who: require full capital protection; are seeking full repayment of investments; are fully risk averse',
  'and/or with a short investment horizon. There may be some risk to capital.',
  'Our investment approach is a long term one which means we may not be suitable for those investors who wish to invest for less than 3 years, but',
  'we believe that our defined investment process with clear parameters for each of our risk mapped model portfolios will go some way to',
  'reducingthe risks associated with investing when used over a 5-10 year period of time.',
  'The composition of this portfolio may be subject to change dependent on the platform or wrap provider used, however this does not change',
  'theoverall risk rating and therefore associated target market . The information contained in this documentation has  been taken from sources',
  'statedand is believed to be reliable and accurate, no information in this document constitutes financial advice.',
  '© 2023 Trust DFM All Rights Reserved.',
  'Portfolio returns in this documentation are calculated using the share classes of the underlying portfolio constituents  from the Advanced',
  'Investment Strategy. The strategy was run by Wills & Trusts IFP Ltd until September 2018 when management of the Advanced Investment',
  'Strategy was delegated to Trust DFM. With all income being reinvested, real portfolio performance may vary from actual portfolio',
  'performance. Past performance is not a guide to future performance and may not be repeated. The value of investments and the income from',
  'them may go down as well as  up and investors may not get back the amounts originally invested. The investment or investment service may not',
  'be suitable for all recipients of this publication and if you have any doubts regarding this, you should contact your Financial Adviser. *The ongoing',
  'cost figures in this documentation are calculated by Trust DFM using the weighted value of the ongoing costs, ex ante of the portfolio',
  'constituents. Where the ongoing costs ex ante is not available the OCF is used. If an underlying instrument has no ongoing costs ex ante or OCF',
  'or TER figure, the portfolio expense cannot be calculated. This report was produced by Collidr Research for Trust DFM using pricing data for',
  'portfolio constituents from Bloomberg. Collidr Research is a trading name of Collidr Technologies Limited, registered in England and Wales with',
  'company no. 09061794 at 34 Southwark Bridge Road, London, SE1 9EU. The information contained in this documentation has been taken from',
  'sources stated and is believed to be reliable and accurate, no information in this document constitutes financial advice.',
  'For more information, please contact your Financial Adviser.',
  'WTDFM Ltd trading as Trust DFM is authorised  and regulated by the Financial Conduct Authority. FRN 782810. Registered in England and Wales',
  'number 10569496. 91-92 High Street, Thame, OXON OX9 3EH',
  '4 of 4Preserve Attenborough',
  '31 Jul 2023',
  'ASSET CLASS PORTFOLIO CHARACTERISTICS',
  'Benchmark PIMFA EQUITY RISK 2 (NET)',
  'Annualised Benchmark Volatility 6.64%',
  'Annualised Portfolio Volatility 5.10%',
  'Ongoing Costs* 0.63%',
  'Total Number of Holdings (ex cash) 20',
  'Fixed Income 28.30% Multi Asset 25.40%',
  'Equity 23.00% Cash 15.80%',
  'Alternatives 7.50%',
  'OBJECTIVES AND POLICY TOP 10 HOLDINGS BY WEIGHT %',
  'This blend aims to balance protecting capital and generating growth',
  'Royal London Short Term Money Market Y Acc 13.80%',
  'over the long term, but with an emphasis on protection. It uses',
  'different asset classes, but with a focus on fixed interest. There is risk TROJAN ETHICAL FND X GBP ACC 11.20%',
  'to capital.',
  'VONTOBEL-24 SUS S/T Bond Inc G 10.00%',
  'The funds in this model meet the minimum criteria of sustainability as',
  'EdenTree Responsible & Sustainable Short Dated Bond B  10.00%',
  'laid out in our Sustainability Policy.',
  'FP FORESIGHT UK INFRA INC-AA 7.50%',
  'The Asset Allocation framework governs how Trust DFM combine',
  'different asset classes, regions and manager styles to optimise Royal London Sustainable Managed Growth C 6.00%',
  'expected returns, but reduce risk.',
  'BMO Responsible Sterling Corproate Bond 2 Acc 4.50%',
  'The current economic and political environment is factored into the',
  'BMO RESPONSIBLE UK EQ 2 ACC 4.50%',
  'portfolio through the quarterly tactical asset allocation. Portfolios are',
  'not automatically rebalanced; we review and adjust as deemed  JPM Global Macro Sustainable Fund GBPH C Acc 4.20%',
  'necessary four times each year following our asset allocation process,',
  'and also in exceptional  circumstances. Liontrust Monthly Inc Bond B Gr Acc 3.80%',
  'There can be no guarantees. The value of Investments may go up and',
  'down and you may get back less than you invested originally.',
  'PORTFOLIO PERFORMANCE',
  'Time Period** 1m 3m 6m 1yr Inception***',
  'Preserve Attenborough 1.2% -0.53% -0.24% -0.49% 2.49%',
  'PIMFA EQUITY RISK 2 (NET) 2.02% 0.31% 0.88% -1.47% 4.96%',
  '**Cumulative returns',
  '***Inception date: 28 Oct 2020',
  '1 of 4Preserve Attenborough',
  '31 Jul 2023',
  'WEIGHTS BY ASSET',
  'Asia Pacific Ex Japan Equities 1.20%',
  'European Equities 2.80%',
  'Fixed Income Multi Asset 3.80%',
  'Credit',
  'UK Equities 6.00%',
  'Alternatives 7.50%',
  'Global Equities 13.00%',
  'Cash 15.80%',
  'Corporate Bonds 24.50%',
  'Global Multi Asset 25.40%',
  '0% 10%  20% 30%',
  'TOP 10 PERFORMANCE CONTRIBUTORS OVER 1 YEAR 1 Aug 2022 - 31 Jul 2023',
  'Investment Contribution',
  'Royal London Short Term Money Market Fund  0.56%',
  'EdenTree Responsible and Sustainable European Equity B 0.52%',
  'Schroder Global Sust Equity Value Z Acc 0.32%',
  'Jupiter Ecology Fund 0.22%',
  'Royal London Sustainable Leaders Trust 0.16%',
  'Vontobel Fund-Twentyfour Sustainable Short Term Bond Income 0.14%',
  'Schroder Core UK Equity Fund 0.12%',
  'BMO Responsible UK Equity 0.08%',
  'Blackrock Global Funds-Circular Economy Fund 0.06%',
  'Baillie Gifford Global Stewardship Fund 0.03%',
  '2 of 4Preserve Attenborough',
  '31 Jul 2023',
  'GROWTH - OVER 1 YEAR',
  'Preserve Attenborough PIMFA EQUITY RISK 2 (NET)',
  '1 Aug 2022 - 31 Jul 2023',
  '102',
  '100',
  '98',
  ')%( 96',
  'htworG)%(',
  '94',
  '92',
  '90',
  '88',
  'Sep Oct Nov Dec Jan Feb Mar Apr May Jun Jul',
  '2023',
  '1 Aug 31 Jul',
  '2022 2023',
  'GROWTH - FROM INCEPTION 28 Oct 2020 - 31 Jul 2023',
  '116',
  '114',
  '112',
  '110',
  '108',
  '106',
  'htworG',
  '104',
  '102',
  '100',
  '98',
  '96',
  '94',
  'Jan Apr Jul Oct Jan Apr Jul Oct Jan Apr Jul',
  '2021 2022 2023',
  '28 Oct 31 Jul',
  '2020 2023',
  'The value of investments and the income from them can go down as well as up and  past performance is not a guide to future',
  'performance.',
  '3 of 4Preserve Attenborough',
  '31 Jul 2023',
  'TARGET MARKET DISCLAIMER',
  'The Attenborough  range is designed for investors where addressing environmental and social challenges is an important consideration. The',
  'product is suitable for retail investors and professional investors.',
  'This portfolio is suitable for inexperienced investors who have a focus on capital preservation and have a low tolerance for market fluctuations.',
  'This portfolio is not suitable for individuals who: require full capital protection; are seeking full repayment  of investments; are fully risk averse',
  'and/or with a short investment horizon. There may be some risk to capital.',
  'Our investment approach is a long term one which means we may not be suitable for those investors who wish to invest for less than 3 years, but',
  'we believe that our defined investment process with clear parameters for each of our risk mapped model portfolios will go some way to',
  'reducingthe risks associated with investing when used over a 5-10 year period of time.',
  'The composition of this portfolio may be subject to change dependent on the platform or wrap provider used, however this does not change',
  'theoverall risk rating and therefore associated target market . The information contained in this documentation has been taken  from sources',
  'statedand is believed to be reliable and accurate, no information in this document constitutes financial advice.',
  '© 2023 Trust DFM All Rights Reserved.',
  'Portfolio returns in this documentation are calculated using the share classes of the underlying portfolio constituents from the Advanced',
  'Investment Strategy. The strategy was run by Wills & Trusts IFP Ltd until September 2018 when management of the Advanced Investment',
  'Strategy was delegated to Trust DFM. With all income being reinvested, real portfolio performance may vary from actual portfolio',
  'performance. Past performance is not a guide to future performance and may not be repeated. The value of investments and the income from',
  'them may go down as well as up and investors may not get back the amounts originally invested. The investment or investment service may not',
  'be suitable for all recipients of this publication and if you have any doubts regarding this, you should contact your Financial Adviser. *The ongoing',
  'cost figures in this documentation are calculated by Trust DFM using the weighted value of the ongoing costs, ex ante of the portfolio',
  'constituents. Where the ongoing costs ex ante is not available the OCF is used. If an underlying instrument has no ongoing costs ex ante or OCF',
  'or TER figure, the portfolio expense cannot be calculated. This report was produced by Collidr Research for Trust DFM using pricing data for',
  'portfolio constituents from Bloomberg. Collidr Research is a trading name  of Collidr Technologies Limited, registered in England and Wales with',
  'company no. 09061794 at 34 Southwark Bridge Road, London, SE1 9EU. The information contained in this documentation has been taken from',
  'sources stated and is believed to be reliable and accurate, no information in this document constitutes financial advice.',
  'For more information, please contact your Financial Adviser.',
  'WTDFM Ltd trading as Trust DFM is authorised and regulated by the Financial Conduct Authority. FRN 782810. Registered in England and Wales',
  'number 10569496. 91-92 High Street, Thame, OXON OX9 3EH',
  '4 of 4Protect Attenborough',
  '31 Jul 2023',
  'ASSET CLASS PORTFOLIO CHARACTERISTICS',
  'Benchmark PIMFA EQUITY RISK 1 (NET)',
  'Annualised Benchmark Volatility 6.38%',
  'Annualised Portfolio Volatility 4.41%',
  'Ongoing Costs* 0.62%',
  'Total Number of Holdings (ex cash) 14',
  'Fixed Income 31.00% Multi Asset 29.00%',
  'Cash 17.00% Equity 15.00%',
  'Alternatives 8.00%',
  'OBJECTIVES AND POLICY TOP 10 HOLDINGS BY WEIGHT %',
  'Our Protect portfolio focuses on protecting capital while generating',
  'Royal London Short Term Money Market Y Acc 15.00%',
  'growth over the long term. It uses different asset classes, with a larger',
  'allocation to fixed interest. There is risk to capital. TROJAN ETHICAL FND X GBP ACC 12.00%',
  'The funds in this model meet the minimum criteria of sustainability as VONTOBEL-24 SUS S/T Bond Inc G 10.00%',
  'laid out in our Sustainability Policy.',
  'EdenTree Responsible & Sustainable Short Dated Bond B 10.00%',
  'The Asset Allocation framework governs how Trust DFM combine',
  'FP FORESIGHT UK INFRA INC-AA 8.00%',
  'different asset classes, regions and manager styles to optimise',
  'expected returns, but reduce risk. Royal London Sustainable Managed Growth C 8.00%',
  'BMO Responsible Sterling Corproate  Bond 2 Acc 6.00%',
  'The current economic and political environment is factored into the',
  'portfolio through the quarterly tactical asset allocation. Portfolios are',
  'Liontrust Monthly Inc Bond B Gr Acc 5.00%',
  'not automatically rebalanced; we review and adjust as deemed',
  'necessary four times each year following our asset allocation process, JPM Global Macro Sustainable Fund GBPH C Acc 5.00%',
  'and also in exceptional circumstances.',
  'BMO RESPONSIBLE UK EQ 2 ACC 4.00%',
  'There can be no guarantees. The value of Investments may go up and',
  'down and you may get back less than you invested originally.',
  'PORTFOLIO PERFORMANCE',
  'Time Period** 1m 3m 6m 1yr Inception***',
  'Protect Attenborough 1.15% -0.85% -0.56% -1.08% 0.64%',
  'PIMFA EQUITY RISK 1  (NET) 1.79% -0.47% -0.25% -4.13% -4.56%',
  '**Cumulative returns',
  '***Inception date: 28 Oct 2020',
  '1 of 4Protect Attenborough',
  '31 Jul 2023',
  'WEIGHTS BY ASSET',
  'European Equities 2.00%',
  'UK Equities 4.00%',
  'Fixed Income Multi Asset 5.00%',
  'Credit',
  'Alternatives 8.00%',
  'Global Equities 9.00%',
  'Cash 17.00%',
  'Corporate Bonds 26.00%',
  'Global Multi Asset 29.00%',
  '0% 10% 20% 30%',
  'TOP 10 PERFORMANCE CONTRIBUTORS OVER 1 YEAR 1 Aug 2022 - 31 Jul 2023',
  'Investment Contribution',
  'Royal London Short Term Money Market Fund 0.63%',
  'EdenTree Responsible and Sustainable European Equity B 0.37%',
  'Schroder Global Sust Equity Value Z Acc 0.30%',
  'Jupiter Ecology Fund 0.20%',
  'Vontobel Fund-Twentyfour Sustainable Short Term Bond Income 0.15%',
  'Royal London Sustainable Leaders Trust 0.13%',
  'BMO Responsible UK Equity 0.07%',
  'Cash 0.00%',
  'JPMorgan Funds - Global Macro Sustainable Fund -0.01%',
  'Trojan Ethical Fund -0.05%',
  '2 of 4Protect Attenborough',
  '31 Jul 2023',
  'GROWTH - OVER 1 YEAR',
  'Protect Attenborough PIMFA EQUITY RISK 1 (NET)',
  '1 Aug  2022 - 31 Jul 2023',
  '102',
  '100',
  '98',
  '96',
  ')%(',
  'htworG)%( 94',
  '92',
  '90',
  '88',
  '86',
  'Sep Oct Nov Dec Jan Feb Mar Apr May Jun Jul',
  '2023',
  '1  Aug 31 Jul',
  '2022 2023',
  'GROWTH - FROM INCEPTION 28 Oct 2020 - 31 Jul 2023',
  '110',
  'Launch date',
  '2021-08-31',
  '108',
  '106',
  '104',
  '102',
  '100',
  'htworG 98',
  '96',
  '94',
  '92',
  '90',
  '88',
  '86',
  'Jan Apr Jul Oct Jan Apr Jul Oct Jan Apr Jul',
  '2021 2022 2023',
  '28 Oct 31 Jul',
  '2020 2023',
  'The value of investments and the income from them can go down as well as up and past performance is not a guide to future',
  'performance.',
  '3 of 4Protect Attenborough',
  '31 Jul 2023',
  'TARGET MARKET DISCLAIMER',
  'The Attenborough range is designed for investors where addressing environmental and social challenges is an important consideration. The',
  'product is suitable for retail investors and professional investors.',
  'This portfolio is suitable for inexperienced investors who have a focus on capital preservation and have a low tolerance for market fluctuations.',
  'This portfolio is not suitable for individuals who: require full capital protection; are seeking full repayment of investments; are fully risk averse',
  'and/or with a short investment horizon. There may be some risk to capital.',
  'Our investment approach is a long term one which means we may not be suitable for those investors who wish to invest for less than 3 years, but',
  'we believe that our defined investment process with clear parameters for each of our risk mapped model portfolios will go some way to reducing',
  'the risks associated with investing when used over a 5-10 year period of time.',
  'The composition of this portfolio may be subject to change dependent on the platform or wrap provider used, however this does not change the',
  'overall risk rating and therefore associated target  market . The information contained in this documentation has been taken from sources stated',
  'and is believed to be reliable and accurate, no information in this document constitutes financial advice.',
  '© 2023 Trust DFM All Rights Reserved.',
  'Portfolio returns in this documentation are calculated using the same share classes of the underlying portfolio constituents from the Advanced',
  'Investment Strategy, or a suitable alternative share class where historic data is not available. The strategy was run by Wills & Trusts IFP Ltd until',
  'September 2018 when management of the Advanced Investment Strategy was delegated to Trust DFM. With all income being reinvested, real',
  'portfolio performance may vary from actual portfolio performance. Past performance is not a guide to future performance and may not be',
  'repeated. The value of investments and the income from them may go down as well as up and investors may not get back the amounts originally',
  'invested. The investment or investment service may not be suitable for all recipients of this publication and if you have any doubts regarding this,',
  'you should contact your Financial Adviser. Historical performance included in this document prior to  the launch date of 31st August 2021 is based',
  'on back testing. Back testing is the process of evaluating an investment strategy by applying it to historical data to simulate what the',
  'performance of such strategy would have been. Back tested performance is purely hypothetical and is provided in this document solely for',
  'informational purposes. Back tested data does not represent actual performance and should not be interpreted as an indication of actual or future',
  'performance. Unlike an actual performance record, hypothetical back-tested performance results do not represent actual trading. In  addition, it',
  'does not involve or take into account that material and market factors may have impacted our decision making, all of which can directly  affect',
  'actual trading results and performance. *The ongoing cost figures in this documentation are calculated by Trust DFM using the weighted value of',
  'the ongoing costs, ex ante of the portfolio constituents. Where the ongoing costs ex ante is not available the Ongoing Charge Figure (OCF) is',
  'used, or the Total Expenses Ratio (TER) if the OCF is unavailable. If an underlying instrument has no ongoing costs ex ante or OCF or TER figure,',
  'the portfolio expense cannot be calculated. This report was produced by Collidr Research for Trust DFM using pricing data for portfolio',
  'constituents from  Bloomberg. Collidr Research is a trading name of Collidr Technologies Limited, registered in England and Wales with company',
  'no. 09061794 at 34 Southwark Bridge Road, London, SE1 9EU. The information contained in this documentation has been taken from sources',
  'stated and is believed to be reliable and accurate, no information in this document constitutes financial advice.For more information, please',
  'contact your Financial Adviser. WTDFM Ltd trading as Trust DFM is authorised and regulated by the Financial Conduct Authority. FRN 782810.',
  'Registered in England and Wales: Company Number 10569496. 91-92 High Street, Thame, OXON OX9 3EH',
  '4 of 4Enjoy Attenborough',
  '31 Jul 2023',
  'ASSET CLASS PORTFOLIO CHARACTERISTICS',
  'Benchmark PIMFA EQUITY RISK 3 (NET)',
  'Annualised Benchmark Volatility 8.17%',
  'Annualised Portfolio Volatility 8.24%',
  'Ongoing Costs* 0.67%',
  'Total Number of Holdings (ex cash) 17',
  'Equity 47.00% Fixed Income 20.00%',
  'Multi Asset 15.00% Cash 12.00%',
  'Alternatives 6.00%',
  'OBJECTIVES AND POLICY TOP 10 HOLDINGS BY WEIGHT %',
  'Our Enjoy portfolio aims to provide capital growth over the long term to',
  'Royal London Short Term Money Market Y Acc 10.00%',
  'support ad-hoc withdrawals through a combination of assets. There is',
  'a moderate risk to capital. VONTOBEL-24 SUS S/T Bond Inc G 10.00%',
  'The funds in this model meet the minimum criteria of sustainability as EdenTree Responsible & Sustainable Short Dated Bond B 10.00%',
  'laid out in our Sustainability Policy.',
  'TROJAN ETHICAL FND X GBP ACC 9.00%',
  'The Asset Allocation framework governs how Trust DFM combine',
  'Schroder Sustainable UK Equity Z Acc 6.00%',
  'different asset classes, regions and manager styles to optimise',
  'expected returns, but reduce risk. BMO RESPONSIBLE UK EQ 2 ACC 6.00%',
  'FP FORESIGHT UK INFRA  INC-AA 6.00%',
  'The current economic and political environment is factored into the',
  'portfolio through the quarterly tactical asset allocation. Portfolios are',
  'Royal London Sustainable Leaders Trust C Inc 6.00%',
  'not automatically rebalanced; we review and adjust as deemed',
  'necessary four times each year following our asset allocation process, EdenTree Responsible & Sust Eurp Eq B 5.00%',
  'and also in exceptional circumstances.',
  'Stewart Investors Asia Pacific Leaders Sustainability',
  '5.00%',
  'There can be no guarantees. The value of Investments may go up and Fund B Acc GBP',
  'down and you may get back less than you invested originally.',
  'PORTFOLIO PERFORMANCE',
  'Time Period** 1m 3m 6m 1yr Inception***',
  'Enjoy Attenborough 1.33% 0.43% 0.68% 1.29% 9.2%',
  'PIMFA EQUITY RISK 3 (NET) 2.19% 1.42% 2.43% 1.65% 16.46%',
  '**Cumulative returns',
  '***Inception date: 28 Oct 2020',
  '1 of 4Enjoy Attenborough',
  '31 Jul 2023',
  'WEIGHTS BY ASSET',
  'Asia Pacific Ex Japan Equities 5.00%',
  'European Equities 5.00%',
  'Alternatives 6.00%',
  'Cash 12.00%',
  'UK  Equities 12.00%',
  'Global Multi Asset 15.00%',
  'Corporate Bonds 20.00%',
  'Global Equities 25.00%',
  '0% 5% 10% 15% 20% 25%',
  'TOP 10 PERFORMANCE CONTRIBUTORS OVER 1 YEAR 1 Aug 2022 - 31 Jul 2023',
  'Investment Contribution',
  'EdenTree Responsible and Sustainable European Equity B 0.94%',
  'Schroder Core UK Equity Fund 0.47%',
  'Schroder Global Sust Equity Value Z Acc 0.40%',
  'Royal London Short Term Money Market Fund 0.34%',
  'Jupiter Ecology Fund 0.27%',
  'Royal London Sustainable Leaders Trust 0.25%',
  'Blackrock Global Funds-Circular Economy Fund 0.25%',
  'Vontobel Fund-Twentyfour Sustainable Short Term Bond Income 0.12%',
  'Baillie Gifford Global Stewardship Fund 0.11%',
  'BMO Responsible UK Equity 0.10%',
  '2 of 4Enjoy Attenborough',
  '31 Jul 2023',
  'GROWTH - OVER 1 YEAR',
  'Enjoy Attenborough PIMFA EQUITY RISK 3 (NET)',
  '1 Aug 2022 - 31 Jul 2023',
  '104',
  '102',
  '100',
  ')%( 98',
  'htworG)%(',
  '96',
  '94',
  '92',
  '90',
  'Sep Oct Nov Dec Jan Feb Mar Apr May Jun Jul',
  '2023',
  '1 Aug 31 Jul',
  '2022 2023',
  'GROWTH - FROM INCEPTION 28 Oct 2020 - 31 Jul 2023',
  '125',
  'Launch date',
  '2021-08-31',
  '120',
  '115',
  'htworG 110',
  '105',
  '100',
  '95',
  'Jan Apr Jul Oct Jan Apr Jul Oct Jan Apr Jul',
  '2021 2022 2023',
  '28 Oct 31 Jul',
  '2020 2023',
  'The value of investments and the income from them can go down as well as up and past performance is not a guide to future',
  'performance.',
  '3 of 4Enjoy Attenborough',
  '31 Jul 2023',
  'TARGET MARKET DISCLAIMER',
  'The Attenborough range is designed for investors where addressing environmental and social challenges is an important consideration. The',
  'product is suitable for retail investors and professional investors.',
  'This portfolio is suitable for investors who are not first time investors with a basic knowledge and experience of investing who have a need for',
  'capital growth and preservation as well as income generation. This portfolio is suitable for those with a moderate tolerance for market fluctuations.',
  'This portfolio is not suitable for individuals who: require full capital protection; are seeking full repayment of investments; are fully risk averse',
  'and/or with  a short investment horizon. There may be some risk to capital.',
  'Our investment approach is a long term one which means we may not be suitable for those investors who wish to invest for less than 3 years, but',
  'we believe that our defined investment process with clear parameters for each of our risk mapped model portfolios will go some way to reducing',
  'the risks associated with investing when used over a 5-10 year period of time.',
  'The composition of this portfolio may be subject to change dependent on the platform or wrap provider used, however this does not change the',
  'overall risk rating and therefore associated target market . The information contained in this documentation has been taken from sources stated',
  'and is believed to be reliable and accurate, no information in this document constitutes financial advice.',
  '© 2023 Trust DFM All Rights Reserved.',
  'Portfolio returns in this documentation are calculated using the same share classes of the underlying portfolio constituents from the Advanced',
  'Investment Strategy, or a suitable  alternative share class where historic data is not available. The strategy was run by Wills & Trusts IFP Ltd until',
  'September 2018 when management of  the Advanced Investment Strategy was delegated to Trust DFM. With all income being reinvested, real',
  'portfolio performance may vary from actual portfolio performance. Past performance is not a guide to future performance and may not be',
  'repeated. The value of investments and the income from them may go down as well as up and investors may not get back the amounts originally',
  'invested. The investment or investment service may not be suitable for all recipients of this publication and if you have any doubts regarding this,',
  'you should contact your Financial Adviser. Historical performance included in this document prior to the launch date of 31st August 2021 is based',
  'on back testing. Back testing is the process of evaluating an investment strategy by applying it to historical data to simulate what the',
  'performance of such strategy would have been. Back tested performance is purely hypothetical and is provided in this document solely for',
  'informational purposes. Back tested data does not represent actual performance and should not be interpreted as an indication of actual or future',
  'performance. Unlike an actual performance record, hypothetical back-tested performance results do not  represent actual trading. In addition, it',
  'does not involve or take into account that material and market factors may have impacted our decision making, all of which can directly affect',
  'actual trading results and performance. *The ongoing cost figures in this documentation are calculated by Trust DFM using the weighted value of',
  'the ongoing costs, ex ante of the portfolio constituents. Where the ongoing costs ex ante is not available the Ongoing Charge Figure (OCF) is',
  'used, or the Total Expenses Ratio (TER) if the OCF is unavailable. If an underlying instrument has no ongoing costs ex ante or OCF or TER figure,',
  'the portfolio expense cannot be calculated. This report was produced by Collidr Research for Trust DFM using pricing data for portfolio',
  'constituents from Bloomberg. Collidr Research is a trading name of Collidr Technologies Limited, registered in England and Wales with company',
  'no. 09061794 at 34 Southwark Bridge Road, London, SE1 9EU. The information contained in this documentation has been taken from sources',
  'stated and is believed to be reliable and accurate, no information in this document constitutes financial advice.For more information, please',
  'contact your Financial Adviser. WTDFM Ltd trading as Trust DFM is authorised and regulated by the Financial Conduct Authority. FRN 782810.',
  'Registered in England and Wales: Company Number 10569496. 91-92 High Street, Thame, OXON OX9 3EH',
  '4 of 4Grow Attenborough',
  '31 Jul 2023',
  'ASSET CLASS PORTFOLIO CHARACTERISTICS',
  'Benchmark PIMFA EQUITY RISK 5 (NET)',
  'Annualised Benchmark Volatility 12.03%',
  'Annualised Portfolio Volatility 13.41%',
  'Ongoing Costs* 0.79%',
  'Total Number of Holdings (ex cash) 18',
  'Equity 90.00% Fixed Income 8.00%',
  'Cash 2.00%',
  'OBJECTIVES AND POLICY TOP 10 HOLDINGS BY WEIGHT %',
  'Our Grow  portfolio seeks growth opportunities and primarily invests in',
  'BMO RESPONSIBLE UK EQ 2 ACC 9.00%',
  'equities. There is a high risk to capital and there can be wide',
  'fluctuations in capital values of investments. EdenTree Responsible & Sustainable Short Dated Bond B 8.00%',
  'The funds in this model meet the minimum criteria of sustainability as Schroder Global Sust Value Eq I Acc 8.00%',
  'laid out in our Sustainability Policy.',
  'Royal London Sustainable Leaders Trust C Inc 8.00%',
  'The Asset Allocation framework governs how Trust DFM combine',
  'Stewart Investors Asia Pacific Leaders Sustainability Fund',
  '8.00%',
  'different asset classes, regions and manager styles to optimise',
  'B Acc GBP',
  'expected returns, but reduce risk.',
  'BMO Responsible  Global Equity 2 Acc 7.00%',
  'The current economic and political environment is factored into the',
  'Jupiter Ecology I Acc 7.00%',
  'portfolio through the quarterly tactical asset allocation. Portfolios are',
  'not automatically rebalanced; we review and adjust as deemed',
  'Regnan Global Equity Impact Solutions A GBP 6.00%',
  'necessary four times each year following our asset allocation process,',
  'and also in exceptional circumstances. Schroder Sustainable UK Equity Z Acc 5.00%',
  'There can be no guarantees. The value of Investments may go up and BGF CIRCULAR ECONOMY D2 GBP Hdg 5.00%',
  'down and you may get back less than you invested originally.',
  'PORTFOLIO PERFORMANCE',
  'Time Period** 1m 3m 6m 1yr Inception***',
  'Grow Attenborough 1.62% 2.33% 1.89%  2.23% 10.82%',
  'PIMFA EQUITY RISK 5 (NET) 2.38% 4.2% 5.89% 8.01% 36.23%',
  '**Cumulative returns',
  '***Inception date: 28 Oct 2020',
  '1 of 4Grow Attenborough',
  '31 Jul 2023',
  'WEIGHTS BY ASSET',
  'Cash 2.00%',
  'European Equities 5.00%',
  'Asia Pacific Ex Japan Equities 8.00%',
  'Corporate Bonds 8.00%',
  'UK  Equities 17.00%',
  'Global Equities 60.00%',
  '0% 20% 40% 60%',
  'TOP 10 PERFORMANCE CONTRIBUTORS OVER 1 YEAR 1 Aug 2022 - 31 Jul 2023',
  'Investment Contribution',
  'Schroder Global Sust Equity Value Z Acc 0.73%',
  'Royal London Sustainable Leaders Trust 0.68%',
  'Jupiter Ecology Fund 0.51%',
  'EdenTree Responsible and Sustainable European Equity B 0.41%',
  'Schroder Core UK Equity Fund 0.39%',
  'Lombard Odier Funds-Climate Transition 0.29%',
  'Regnan Global Equity Impact Solutions/United Kingdom 0.24%',
  'BMO Responsible UK Equity 0.20%',
  'Regnan UK Umbrella Fund-Regnan Sustainable Water & Waste Fund 0.14%',
  'Edentree Responsible & Sustainable Short Dated Bond Fund 0.05%',
  '2 of 4Grow Attenborough',
  '31 Jul 2023',
  'GROWTH - OVER 1 YEAR',
  'Grow Attenborough PIMFA EQUITY RISK 5 (NET)',
  '1 Aug 2022 - 31 Jul 2023',
  '110',
  '108',
  '106',
  '104',
  '102',
  ')%(',
  'htworG)%( 100',
  '98',
  '96',
  '94',
  '92',
  '90',
  'Sep Oct Nov Dec Jan Feb Mar Apr May Jun Jul',
  '2023',
  '1 Aug 31 Jul',
  '2022 2023',
  'GROWTH - FROM INCEPTION 28 Oct 2020 - 31 Jul 2023',
  '140',
  'Launch date',
  '2021-08-31',
  '135',
  '130',
  '125',
  '120',
  'htworG',
  '115',
  '110',
  '105',
  '100',
  '95',
  'Jan Apr Jul Oct Jan Apr Jul Oct Jan Apr Jul',
  '2021 2022 2023',
  '28  Oct 31 Jul',
  '2020 2023',
  'The value of investments and the income from them can go down as well as up and past performance is not a guide to future',
  'performance.',
  '3 of 4Grow Attenborough',
  '31 Jul 2023',
  'TARGET MARKET DISCLAIMER',
  'The Attenborough range is designed for investors where addressing  environmental and social challenges is an important consideration. The',
  'product is suitable for retail investors and professional investors.',
  'This portfolio is suitable for those with a high tolerance for market fluctuations. You must understand you are taking on a high level of risk and',
  'there could be wide fluctuations in the capital values of your investments. There is a high risk to capital.',
  'This portfolio is not suitable for individuals who: require full capital protection; are seeking full repayment of investments; are fully risk averse',
  'and/or with a short investment horizon. There may be some risk to capital.',
  'Our investment approach is a long term one which means we may not be suitable for those investors who wish to invest for  less than 3 years, but',
  'we believe that our defined investment process with clear parameters for each of our risk mapped model portfolios will go some way to reducing',
  'the risks associated with investing when used over a 5-10 year period of time.',
  'The composition of this portfolio may be subject to change dependent on the platform or wrap provider used, however this does not change the',
  'overall risk rating and therefore associated target market . The information contained in this documentation has been taken from sources stated',
  'and is believed to be reliable and accurate, no information in  this document constitutes financial advice.',
  '© 2023 Trust DFM All Rights Reserved.',
  'Portfolio returns in this documentation are calculated using the same share classes of the underlying portfolio constituents from the Advanced',
  'Investment Strategy, or a suitable alternative share class where historic data is not available. The strategy was run by Wills & Trusts IFP Ltd until',
  'September 2018 when management of the Advanced Investment Strategy was delegated to Trust DFM. With all income being reinvested, real',
  'portfolio performance may vary from actual portfolio performance. Past performance is not a guide to future performance and may not be',
  'repeated. The value of investments and the income from them may go down as well as up and investors may not get back the amounts originally',
  'invested. The investment or investment service may not be suitable for all recipients of this publication and if you have any doubts regarding this,',
  'you should contact your Financial Adviser. Historical performance included in this document prior to the launch date of 31st August 2021 is based',
  'on back testing. Back testing is the process of evaluating an investment strategy by applying it to historical data to simulate what the',
  'performance of such strategy would have been. Back tested performance is purely hypothetical and is provided in this document solely for',
  'informational purposes. Back tested data does not represent actual performance and should not be interpreted as an indication of actual or future',
  'performance. Unlike an actual performance record, hypothetical back-tested performance results do not represent actual trading. In addition, it',
  'does not involve or take into account that material and market factors may have impacted our decision making, all of which can directly affect',
  'actual trading results and performance. *The ongoing cost figures in this documentation are calculated by Trust DFM using the weighted value of',
  'the ongoing costs, ex ante of the portfolio constituents. Where the ongoing costs ex ante is not available the Ongoing Charge Figure (OCF) is',
  'used, or the Total Expenses Ratio (TER) if the OCF is unavailable. If an underlying instrument has no ongoing costs ex ante or OCF or TER figure,',
  'the portfolio expense cannot be calculated. This report was produced by Collidr Research for Trust DFM using pricing data for portfolio',
  'constituents from Bloomberg. Collidr Research is a trading name of Collidr Technologies Limited, registered in England and Wales with company',
  'no. 09061794 at 34 Southwark Bridge Road, London, SE1 9EU. The information contained in this documentation has been taken from sources',
  'stated and is believed to be reliable and accurate, no information in this document constitutes financial advice.For more information, please',
  'contact your Financial Adviser. WTDFM Ltd trading as Trust DFM is authorised and regulated by the Financial Conduct Authority. FRN 782810.',
  'Registered in England and Wales: Company Number 10569496. 91-92 High Street, Thame, OXON OX9 3EH',
  '4 of 4'
]


for line in text[:5]:
    match = re.search(r'\d{2}\.\d{2}\.\d{4}', line)
    if match:
        date = match.group()

    for i, line in enumerate(text):
        if 'Annual management charge' in line:
            for offset in range(0, 2):  # check other lines
                if i + offset < len(text):  # check if line is exist
                    founded_line = text[i+offset].strip()
                    if re.search(r'\d+\.\d+%', founded_line):  # if pattern found
                        perscent_pattern = r'\d+\.\d+%'
                        AMC = re.findall(perscent_pattern, founded_line)[0].replace('%','')

        if 'OCF ' in line:
            parts = line.split('%')  # split by '%'
            OCF = parts[0].strip().split()[1]  # take only first part and then add '%'
        
        if '3M 6M 1Y 3Y 5Y' in line:
            for offset in range(1, 4):  # check other lines
                if i + offset < len(text):  # check if line is exist
                    founded_line = text[i + offset].strip()
                    matches = re.findall(r'[+-]?\d+\.\d+', founded_line)
                    print(founded_line)
                    if len(matches) >= 3 and first_line_found == False:
                        cleaned_line = re.sub(r'.*?(MPS.*)', r'\1', founded_line)
                        numbers = re.findall(r'[+-]?\d+\.\d+', cleaned_line)
                        one_year = float(numbers[2])
                        first_line_found =True
    print(date)
    print(AMC)
    print(OCF)
    print(one_year)
    